### ISSUE TITLE
"HTTP Basic Authentication is not supported for this API" Error

### ISSUE THREAD

**Issue by filiusfob** [burnash/gspread#1024]
Hi,
Sorry if I'm missing something really straightforward, here, and I would post this as a question on somewhere like stackoverlfow, but searching there, I get no hits using the "gspread" tag for the response error message **"HTTP Basic Authentication is not supported for this API"**, and only a handful of unhelpful hits (in English) on the whole web with Google.

I note that there have been previous issues with 401 errors regarding insufficient privileges for gspread on the github page, but apparently none relating specifically to the response error message "HTTP Basic Authentication is not supported for this API".

HTTP Basic Authentication is where the password is contained in a header, essentially in cleartext, support for which was discontinued by Google several years ago. I'm not sure why code under the hood would be reverting to this approach.

I have installed all the relevant `gspread` and Google authorisation libraries in a virtual environment to try to avoid any problems with incompatible library versions 

To try to provide useful information, I turned on logging, and also added some debugging print calls whose outputs all start with "***". I added 3 such print calls to `Client.request()` in the `gspread` code. 
Here are my answers to the github boilerplate questions:

**To Reproduce**
1. Run the code listed below... on my setup, I guess.
2. Watch it fail
3. Try with `curl` using the same authentication code in the header that was printed out in the sample code and watch it access the Google Drive data successfully.

**Expected behavior**
I expect the library to sort out the Google authentication business per the `gspread` documentation.

**Code example***
Here is code that produces the problem. 
```python
import gspread
import logging

GOOGLE_SERVICE_ACCOUNT_KEY_FILE="syllabus-from-spreadsh-344712-119d6b4c8a7e.json"

logging.basicConfig(level=logging.DEBUG)

SCOPES = [
	'https://www.googleapis.com/auth/spreadsheets',
	'https://www.googleapis.com/auth/drive'
]

from google.oauth2.service_account import Credentials
T_KEY_FILE, scopes=SCOPES)
credentials=Credentials.from_service_account_file(GOOGLE_SERVICE_ACCOUNT_KEY_FILE, scopes=SCOPES)
gc=gspread.authorize(credentials) #gc is gspread.client.Client object
gc.login()

print(gc.list_spreadsheet_files())
```
A typical output is:
```
python3 build_agenda.py 
DEBUG:urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): oauth2.googleapis.com:443
DEBUG:urllib3.connectionpool:https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): oauth2.googleapis.com:443
DEBUG:urllib3.connectionpool:https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
***endpoint== https://www.googleapis.com/drive/v3/files
***headers== None
***self.session.headers== {'User-Agent': 'python-requests/2.27.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Authorization': 'Bearer ya29.c.b0AXv0zTNZ9YItED8XCrIjNaPgJZGeWVdFsubVI-6RX3eOX2uIVXLWBgwJsz5UQLlVl-v2atCBOho9lhWEWnF6w5C3BGXWT8er9WD0ljFBwZrIB0jC_rP__AJw216JWAwqbKDR0y259fZkShlMVRVNbLD9j3qDDLmhQZsdVorAEdDZVdaQZjXDCCLwqS5T2wFCX_4afKiHPhv9P8TyD3e9TXmPzBynTUj0.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................'}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.googleapis.com:443
DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "GET /drive/v3/files?q=mimeType%3D%22application%2Fvnd.google-apps.spreadsheet%22&pageSize=1000&supportsAllDrives=True&includeItemsFromAllDrives=True&fields=kind%2CnextPageToken%2Cfiles%28id%2Cname%2CcreatedTime%2CmodifiedTime%29 HTTP/1.1" 401 None
INFO:google.auth.transport.requests:Refreshing credentials due to a 401 response. Attempt 1/2.
DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
DEBUG:urllib3.connectionpool:https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "GET /drive/v3/files?q=mimeType%3D%22application%2Fvnd.google-apps.spreadsheet%22&pageSize=1000&supportsAllDrives=True&includeItemsFromAllDrives=True&fields=kind%2CnextPageToken%2Cfiles%28id%2Cname%2CcreatedTime%2CmodifiedTime%29 HTTP/1.1" 401 None
INFO:google.auth.transport.requests:Refreshing credentials due to a 401 response. Attempt 2/2.
DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
DEBUG:urllib3.connectionpool:https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "GET /drive/v3/files?q=mimeType%3D%22application%2Fvnd.google-apps.spreadsheet%22&pageSize=1000&supportsAllDrives=True&includeItemsFromAllDrives=True&fields=kind%2CnextPageToken%2Cfiles%28id%2Cname%2CcreatedTime%2CmodifiedTime%29 HTTP/1.1" 401 None
Traceback (most recent call last):
  File "/home/marca/dev/rostrum/agenda_from_google_spreadsheet/build_agenda.py", line 68, in <module>
    print(gc.list_spreadsheet_files())
  File "/home/marca/dev/rostrum/agenda_from_google_spreadsheet/venv/lib/python3.9/site-packages/gspread/client.py", line 123, in list_spreadsheet_files
    res = self.request("get", url, params=params).json()
  File "/home/marca/dev/rostrum/agenda_from_google_spreadsheet/venv/lib/python3.9/site-packages/gspread/client.py", line 98, in request
    raise APIError(response)
gspread.exceptions.APIError: {'errors': [{'domain': 'global', 'reason': 'authError', 'message': 'HTTP Basic Authentication is not supported for this API', 'locationType': 'header', 'location': 'Authorization'}], 'code': 401, 'message': 'HTTP Basic Authentication is not supported for this API'}
```

If I use the same authorisation code with `curl`, copied and pasted from the output of the gspread/python execution, the response is successful, showing me a list of the sole, shared file on the Google drive:
 ```
curl -v -H "Authorization: Bearer ya29.c.b0AXv0zTNZ9YItED8XCrIjNaPgJZGeWVdFsubVI-6RX3eOX2uIVXLWBgwJsz5UQLlVl-v2atCBOho9lhWEWnF6w5C3BGXWT8er9WD0ljFBwZrIB0jC_rP__AJw216JWAwqbKDR0y259fZkShlMVRVNbLD9j3qDDLmhQZsdVorAEdDZVdaQZjXDCCLwqS5T2wFCX_4afKiHPhv9P8TyD3e9TXmPzBynTUj0......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................." https://www.googleapis.com/drive/v3/files
*   Trying 216.58.214.10:443...
*   Trying 2a00:1450:400e:801::200a:443...
* Connected to www.googleapis.com (216.58.214.10) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=upload.video.google.com
*  start date: Mar 21 03:17:22 2022 GMT
*  expire date: Jun 13 03:17:21 2022 GMT
*  subjectAltName: host "www.googleapis.com" matched cert's "*.googleapis.com"
*  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1C3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55bdbc14a560)
> GET /drive/v3/files HTTP/2
> Host: www.googleapis.com
> user-agent: curl/7.74.0
> accept: */*
> authorization: Bearer ya29.c.b0AXv0zTNZ9YItED8XCrIjNaPgJZGeWVdFsubVI-6RX3eOX2uIVXLWBgwJsz5UQLlVl-v2atCBOho9lhWEWnF6w5C3BGXWT8er9WD0ljFBwZrIB0jC_rP__AJw216JWAwqbKDR0y259fZkShlMVRVNbLD9j3qDDLmhQZsdVorAEdDZVdaQZjXDCCLwqS5T2wFCX_4afKiHPhv9P8TyD3e9TXmPzBynTUj0.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 200 
< cache-control: no-cache, no-store, max-age=0, must-revalidate
< pragma: no-cache
< expires: Mon, 01 Jan 1990 00:00:00 GMT
< date: Thu, 07 Apr 2022 15:37:31 GMT
< vary: X-Origin
< vary: Origin,Accept-Encoding
< content-type: application/json; charset=UTF-8
< x-content-type-options: nosniff
< x-frame-options: SAMEORIGIN
< content-security-policy: frame-ancestors 'self'
< x-xss-protection: 1; mode=block
< server: GSE
< alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
< accept-ranges: none
< 
{
 "kind": "drive#fileList",
 "incompleteSearch": false,
 "files": [
  {
   "kind": "drive#file",
   "id": "1zHgcJUvPzZ0vdNS6fdp8Euey1pT9eRC3b03RpVlUz6s",
   "name": "2022 Syllabus for Rostrum NSW Club 15",
   "mimeType": "application/vnd.google-apps.spreadsheet"
  }
 ]
}
* Connection #0 to host www.googleapis.com left intact
```
(The presence or absence of all those dots seems to make no difference.)

I also added a line to `Client.request()` that accumulates responses so that they can be inspected later. I've only ever observed it to accumulate 1 response, which is the response you see from the `APIError`, so I didn't include the code that shows this in order to keep the test code simpler.

**Environment info:**
- Debian Linux w/ kernel version 5.13.3
- Python 3.9.2
- gspread 5.3.0

Any help you could provide would be greatly appreciated.
Thanks!

**Comment by filiusfob** [comment]
OK, so I figured it out. I had a `~/.netrc` file lying around from something I was doing years ago. In the `requests` library that Google's authentication libraries use, the contents of `~/.netrc` are picked up and used to try to log in using HTTP Basic Authentication if the authentication information is `None` at certain points.

The solution is to move or delete the `~/.netrc` file. One can also do:
```python
import requests
requests.utils.NETRC_FILES=[]
```
There might be smarter ways within `gspread` or the Google authentication code that pass a non-`None` value for `auth` earlier, so that the `requests` library never goes looking for `~/.netrc`, but the above solution works for me now.

This might help someone.
