### ISSUE TITLE
append_row(values) - HTTP Error 400 Bad request

### ISSUE THREAD

**Issue by JosefJezek** [burnash/gspread#111]
```
row = ['a', 'b']
ws.append_row(row)
```

Traceback (most recent call last):
  File "./mag2gs.py", line 11, in <module>
    ws.append_row(row)
  File "/usr/local/lib/python2.7/dist-packages/gspread-0.1.0-py2.7.egg/gspread/models.py", line 510, in append_row
    self.add_rows(1)
  File "/usr/local/lib/python2.7/dist-packages/gspread-0.1.0-py2.7.egg/gspread/models.py", line 495, in add_rows
    self.resize(rows=self.row_count + rows)
  File "/usr/local/lib/python2.7/dist-packages/gspread-0.1.0-py2.7.egg/gspread/models.py", line 488, in resize
    self._element = self.client.put_feed(uri, ElementTree.tostring(feed))
  File "/usr/local/lib/python2.7/dist-packages/gspread-0.1.0-py2.7.egg/gspread/client.py", line 249, in put_feed
    raise ex
gspread.httpsession.HTTPError

**Comment by msuozzo** [comment]
This issue seems to be resolved. Feel free to reply if this is not the case.
