### ISSUE TITLE
HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by Link-** [burnash/gspread#118]
Hi,

Is there a limit to the cell range I can call for?! Same call for smaller ranges works fine...

worksheet.range('A1:K206')

Traceback (most recent call last):
  File "/autoret.py", line 72, in <module>
    cell_list = wkS.range('A1:K206')
  File "/Library/Python/2.7/site-packages/gspread/models.py", line 319, in range
    'return-empty': 'true'})
  File "/Library/Python/2.7/site-packages/gspread/client.py", line 219, in get_cells_feed
    r = self.session.get(url)
  File "/Library/Python/2.7/site-packages/gspread/httpsession.py", line 68, in get
    return self.request('get', url, **kwargs)
  File "/Library/Python/2.7/site-packages/gspread/httpsession.py", line 65, in request
    raise e
urllib2.HTTPError: HTTP Error 400: Bad Request

**Comment by msuozzo** [comment]
Sorry for the slow response.

Were you able to reproduce this for the `range` call you described?
