### ISSUE TITLE
Http Session error while updating cell value in new google spreadsheet

### ISSUE THREAD

**Issue by nirvesh0103** [burnash/gspread#123]
I am able to open google spread sheet and also able fetch all the data, but when I am trying to update cell value got gspread.httpsession.HTTPError
Traceback (most recent call last):
  File "/Main.py", line 29, in <module>
    main.fetchReadings()
  File "/Main.py", line 22, in fetchReadings
    fod.fetchAndInsertData(self.startRow, sys.argv[3])
  File "fetchAndInsertData.py", line 97, in fetchAndInsertData
    worksheet.update_cell(START_ROW, 7, time)
  File "build/bdist.macosx-10.8-intel/egg/gspread/models.py", line 426, in update_cell
  File "build/bdist.macosx-10.8-intel/egg/gspread/client.py", line 250, in put_feed
gspread.httpsession.HTTPError

**Comment by g0t0wasd** [comment]
After adding lines that @sadovnychyi proposed I'm getting next error:
    



    Traceback (most recent call last):
      File "updater.py", line 89, in <module>
        update_data()
      File "updater.py", line 87, in update_data
        process_entries(users)
      File "updater.py", line 63, in process_entries
        populate_worksheet(wksht, user_entries)
      File "updater.py", line 41, in populate_worksheet
        worksheet = clear(worksheet)
      File "updater.py", line 31, in clear
        sht.add_worksheet("Temp", 1, 1)
      File "/usr/local/lib/python3.4/dist-packages/gspread/models.py", line 89, in add_worksheet
        elem = self.client.post_feed(url, ElementTree.tostring(feed))
      File "/usr/local/lib/python3.4/dist-packages/gspread/client.py", line 289, in post_feed
        raise RequestError(message)
    gspread.exceptions.RequestError: POST method does not support concurrency

Had to remove "POST", so `if method in ['PUT', 'POST']:` became `if method == 'PUT':`. Seems to work now, but I'm not sure is it ok?
Am I only who issuing such problem?

**Comment by sadovnychyi** [comment]
@g0t0wasd those changes were merged into master long time ago, you don't have to add anything manually anymore. Look on https://github.com/burnash/gspread/pull/127

Maybe you experiencing some new bug and should fill new issue for it.
