### ISSUE TITLE
Typo in `oauth_from_dict`

### ISSUE THREAD

**Issue by mgilski** [burnash/gspread#1394]
**Describe the bug**

Calling 
```
gspread.oauth_from_dict(credentials)
```
raises
```
TypeError: local_server_flow() got an unexpected keyword argument 'scopres'
```

Looks like a typo.

**Environment info:**
- macOs
- Python 3.12
- gspread 6.0.0

**Stack trace**
```
Traceback (most recent call last):
  File "/Users/maciej/dev/supportiv/content-deployment/src/main.py", line 3, in <module>
    from src.services.process_sheets import get_new_content
  File "/Users/maciej/dev/supportiv/content-deployment/src/services/process_sheets.py", line 21, in <module>
    client, _ = gspread.oauth_from_dict(FIREBASE_CREDS)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maciej/dev/supportiv/content-deployment/.venv/lib/python3.12/site-packages/gspread/auth.py", line 264, in oauth_from_dict
    creds = flow(client_config=credentials, scopres=scopes)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: local_server_flow() got an unexpected keyword argument 'scopres'
```

**Comment by alifeee** [comment]
this does look like a typo. Thanks for making the issue :))
