### ISSUE TITLE
Update examples of gspread usage /Readme.md 

### ISSUE THREAD

**Issue by lightdrk** [burnash/gspread#1410]
Hi, 

Their is no usage example of single cell update in the Read me as the example currently is not complete . 
simple add worksheet.update_acell('A1', 'Bingo!') to the updating cell example

**Comment by alifeee** [comment]
Hi. Thanks for the issue :)

Do you refer to this section of the readme?

https://github.com/burnash/gspread/blob/4a48fbdc4bc56724d3a1d8fcdb7f5793fb58f160/README.md#L263-L267

I notice that this section is wrong. I think it should be 

```diff
# Update a single cell
-worksheet.update('B1', 'Bingo!')
+worksheet.update_acell('B1', 'Bingo!')

# Update a range
-worksheet.update('A1:B2', [[1, 2], [3, 4]])
+worksheet.update([[1, 2], [3, 4]], 'A1:B2')
```

I think that all functions in the readme should be tested to make sure they work, as that is the most important part of documentation to get right. This could be as a part of #1413

**Comment by lightdrk** [comment]
Yes , dont know about range but yes for the single one

**Comment by jeeeepp** [comment]
I have some problems with updating single cell.
```python
from selenium import webdriver
from google.oauth2.service_account import Credentials
import gspread
from humanfriendly import parse_size
from selenium import webdriver
from selenium.webdriver.common.by import By
scopes = [
    'https://www.googleapis.com/auth/spreadsheets',
    'https://www.googleapis.com/auth/drive'
]

credentials = {
 ******
}
likes=[]
comments=[]
saves=[]
shares=[]

gc = gspread.service_account_from_dict(credentials)
sht2 = gc.open_by_url('https://docs.google.com/spreadsheets/d/1zZFqgrN6A4JNIlftQgpbyMHBZadfefFWsU7LpL_BBrwQxu6E/edit?usp=sharing')
worksheet = sht2.get_worksheet(0)
worksheet.update('B1', 'Bingo!')
``` 

I got an error.  I ever done this in the last week before but the scripts are working.
```python
gspread.exceptions.APIError: {'code': 400, 'message': 'Invalid value at \'data.values\' (type.googleapis.com/google.protobuf.ListValue), "A2"', 'status': 'INVALID_ARGUMENT', 'details': [{'@type': 'type.googleapis.com/google.rpc.BadRequest', 'fieldViolations': [{'field': 'data.values', 'description': 'Invalid value at \'data.values\' (type.googleapis.com/google.protobuf.ListValue), "A2"'}]}]}
PS C:\Users\Lenovo\Desktop\code\tiktoka-data-mcn>
PS C:\Users\Lenovo\Desktop\code\tiktoka-data-mcn>
PS C:\Users\Lenovo\Desktop\code\tiktoka-data-mcn>
PS C:\Users\Lenovo\Desktop\code\tiktoka-data-mcn> python '.\test,py'
Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\code\tiktoka-data-mcn\test,py", line 34, in <module>
    worksheet.update('B1', 'Bingo!')
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python311\site-packages\gspread\worksheet.py", line 1239, in update
    response = self.client.values_update(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python311\site-packages\gspread\http_client.py", line 168, in values_update
    r = self.request("put", url, params=params, json=body)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python311\site-packages\gspread\http_client.py", line 123, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 400, 'message': 'Invalid value at \'data.values\' (type.googleapis.com/google.protobuf.ListValue), "B1"', 'status': 'INVALID_ARGUMENT', 'details': [{'@type': 'type.googleapis.com/google.rpc.BadRequest', 'fieldViolations': [{'field': 'data.values', 'description': 'Invalid value at \'data.values\' (type.googleapis.com/google.protobuf.ListValue), "B1"'}]}]}
```

**Comment by alifeee** [comment]
> I have some problems with updating single cell.

Hi. Apologies for the delay.

Please change your code to

```diff
- worksheet.update("B1", "Bingo!")
+ worksheet.update_acell("B1", "Bingo!")
```

and let me know if this works?

We will update the readme to reflect this soon :)

Thanks.

p.s. to @lavigne958: are the arguments of `update` and `update_acell` different to one another? I feel the answer is yes.

**Comment by lavigne958** [comment]
yes they are ! :disappointed: 

the method `update` is `update(<values>, <range name>, ...)`
the method `update_acell is `update_acell(<cell A1 notation>, <value>)`

**Comment by alifeee** [comment]
nice how did this happen

**Comment by lavigne958** [comment]
> nice how did this happen

I would say it's historic, left over from the past from this repository I suppose.
