### ISSUE TITLE
Getting HTTPException for deadline exceeded from sheets URL

### ISSUE THREAD

**Issue by wprater** [burnash/gspread#192]
This happens intermittently, and even after 6-7 seconds or so.  Im on GAE and I've tried to increase the fetch limit for the client code that's calling gspread, but I suspect something else is going on.

Thoughts?  Why would the deadline claim to be exceeded only after less than 10 seconds?

**Comment by burnash** [comment]
Could you post your code sample please?

**Comment by wprater** [comment]
here is a small extraction.  nothing fancy going on here.

```
        scope = ['https://spreadsheets.google.com/feeds']

        credentials = SignedJwtAssertionCredentials(
            DEVELOPER_SERVICE_ACCOUNT,
            SIGNED_KEY,
            scope)
        self.gc = gspread.Client(auth=credentials)
        self.gc.login()

        spreadsheet = self.gc.open_by_key(INITIAL_REWARDS_KEY)
        spreadsheet.get_worksheet(0).get_all_values()
```

**Comment by wprater** [comment]
any thoughts?  strange that it's so intermittent and not much time elapses.

**Comment by coto** [comment]
@burnash is there any way to set a deadline for comunnication with Google Data API?

**Comment by msuozzo** [comment]
Could you could timeout and retry? There's probably a long tail for responses so you could assume any request taking longer than N seconds is not worth waiting for. This would only work with idempotent operations, though.

**Comment by coto** [comment]
@msuozzo how do you timeout?

**Comment by coto** [comment]
I got this exception intermitently 

Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/Users/coto/beecoss/calexpense/web/models/spreadsheet_write.py", line 103, in get
    ws_help.update_acell('B5',str("0" if summary_ca.value == 0 else summary_ca.value) )
  File "/Users/coto/beecoss/calexpense/web/models/../libs/gspread/models.py", line 429, in update_acell
    return self.update_cell(*(self.get_int_addr(label)), val=val)
  File "/Users/coto/beecoss/calexpense/web/models/../libs/gspread/models.py", line 440, in update_cell
    self._cell_addr(row, col))
  File "/Users/coto/beecoss/calexpense/web/models/../libs/gspread/client.py", line 271, in get_cells_cell_id_feed
    r = self.session.get(url)
  File "/Users/coto/beecoss/calexpense/web/models/../libs/gspread/httpsession.py", line 79, in get
    return self.request('GET', url, **kwargs)
  File "/Users/coto/beecoss/calexpense/web/models/../libs/gspread/httpsession.py", line 72, in request
    response = self.connections[uri.scheme + uri.netloc].getresponse()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/dist27/gae_override/httplib.py", line 526, in getresponse
    raise HTTPException(str(e))
HTTPException: Deadline exceeded while waiting for HTTP response from URL: https://spreadsheets.google.com/feeds/cells/1J0Q3ZCG1bwXAP35zveLulz0eyAuCUQSxOkz-6AcM9Y4/o1nizun/private/full/R7C2

**Comment by msuozzo** [comment]
Alright, as luck would have it, I was struggling with that exception a few weeks ago. Basically, this is an AppEngine-specific exception put in place so a single request doesn't last indefinitely. AppEngine is giving up on trying to run your code (which is calling `gspread`) because it's taking too long (you can verify the default timeout by calling [this](https://cloud.google.com/appengine/docs/python/refdocs/google.appengine.api.urlfetch#google.appengine.api.urlfetch.get_default_fetch_deadline) function on AppEngine).

@wprater check out [this](https://cloud.google.com/appengine/docs/python/refdocs/google.appengine.api.urlfetch#google.appengine.api.urlfetch.set_default_fetch_deadline) urlfetch function to increase the deadline for AppEngine. This should prevent your requests from failing so quickly.

Unfortunately, there is currently no way to enforce a timeout in gspread (I believe this is what you were asking for, @coto). A timeout would allow you to recover from a bad session and meet AppEngine's deadline. There is an out-standing feature request (#280) tracking progress on the matter and it remains a priority for the project.

I'm going to close this issue out as it will be solvable once #280 is closed.
