### ISSUE TITLE
HTTPError Exception via insert_row

### ISSUE THREAD

**Issue by mweinelt** [burnash/gspread#194]
```
Traceback (most recent call last):
  File "runner.py", line 144, in <module>
    lat=lat, lng=lng, photo=portal['image'], address=portal['address'])
  File "project/sheet.py", line 104, in insert
    self.sheet.insert_row(values, row)
  File "project/.venv/lib/python3.4/site-packages/gspread-0.2.2-py3.4.egg/gspread/models.py", line 549, in insert_row
  File "project/.venv/lib/python3.4/site-packages/gspread-0.2.2-py3.4.egg/gspread/models.py", line 514, in add_rows
  File "project/.venv/lib/python3.4/site-packages/gspread-0.2.2-py3.4.egg/gspread/models.py", line 507, in resize
  File "project/.venv/lib/python3.4/site-packages/gspread-0.2.2-py3.4.egg/gspread/client.py", line 277, in put_feed
  File "project/.venv/lib/python3.4/site-packages/gspread-0.2.2-py3.4.egg/gspread/client.py", line 271, in put_feed
  File "project/.venv/lib/python3.4/site-packages/gspread-0.2.2-py3.4.egg/gspread/httpsession.py", line 88, in put
  File "project/.venv/lib/python3.4/site-packages/gspread-0.2.2-py3.4.egg/gspread/httpsession.py", line 75, in request
gspread.httpsession.HTTPError: <http.client.HTTPResponse object at 0x7f3200245198>
```

**Comment by burnash** [comment]
I've updated gspread so now it returns a message along with this exception. Can you update the library, rerun your code and post the exception message?

**Comment by mweinelt** [comment]
The code is not in use any more, sorry.
