### ISSUE TITLE
httplib.BadStatusLine: ''

### ISSUE THREAD

**Issue by timkofu** [burnash/gspread#209]
Hello,

Today I'm getting the exception below:

Traceback (most recent call last):
  File "code_base/dothings.py", line 69, in <module>
    updateg()
  File "code_base/dothings.py", line 57, in updateg
    sheet = gsheet.open('things').worksheet(dits[g][1])
  File "/opt/anaconda/lib/python2.7/site-packages/gspread/client.py", line 134, in open
    feed = self.get_spreadsheets_feed()
  File "/opt/anaconda/lib/python2.7/site-packages/gspread/client.py", line 220, in get_spreadsheets_feed
    r = self.session.get(url)
  File "/opt/anaconda/lib/python2.7/site-packages/gspread/httpsession.py", line 79, in get
    return self.request('GET', url, **kwargs)
  File "/opt/anaconda/lib/python2.7/site-packages/gspread/httpsession.py", line 72, in request
    response = self.connections[uri.scheme+uri.netloc].getresponse()
  File "/opt/anaconda/lib/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/opt/anaconda/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/opt/anaconda/lib/python2.7/httplib.py", line 379, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''

I'm using the latest github source (cloned just a few minutes ago).

**Comment by philfreo** [comment]
Same here. What's this from?

**Comment by philfreo** [comment]
This fixed it for me:
https://github.com/burnash/gspread/issues/157#issuecomment-53970265

**Comment by flyte** [comment]
As mentioned on https://github.com/burnash/gspread/issues/157#issuecomment-143575514 it would be good to have the library either raise a better error or handle the reauthorization internally so that we don't have to keep going back to authorise_credentials() every time we get the BadStatusLine exception.

Perhaps there already is a way to handle this? If so, it'd be great to get that in the readme.
