### ISSUE TITLE
xml.etree.ElementTree.ParseError: mismatched tag: line 2, column 26

### ISSUE THREAD

**Issue by ibegoldex** [burnash/gspread#215]
Hello, all operations work good, but now how this error:

Traceback (most recent call last):
  File "youprint/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 453, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 77, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/bmk/youprint/index/management/commands/precios.py", line 7, in <module>
    sh = gc.open('precios bmk2')
  File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 134, in open
    feed = self.get_spreadsheets_feed()
  File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 221, in get_spreadsheets_feed
    return ElementTree.fromstring(r.read())
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: mismatched tag: line 2, column 26

**Comment by burnash** [comment]
@ibegoldex It's hard to tell what's wrong from your stacktrace. It looks like Google server has responded with wrong XML. Could you please debug it more and post an XML the API has responded with?

**Comment by ibegoldex** [comment]
okay, im try to comment more information , but im say, all fi.e also new file, show this error.

**Comment by ibegoldex** [comment]
Yes, you are correct, im think that google change same configuration and gspread need to update, but right now work, and google sendme samething wrong, thanks.

**Comment by burnash** [comment]
That's what I'm saying. If you can post the XML response you're getting, I can figure out what to update.

**Comment by msuozzo** [comment]
This matter cannot be dealt with if we have no way to reproduce the issue. If the issue has persisted with new versions of gspread and you are able to do so, please post an XML dump when the error occurs.

Thank you for reporting this issue
