### ISSUE TITLE
ResponseNotReady Exceptions

### ISSUE THREAD

**Issue by rmminusrslash** [burnash/gspread#216]
Hey guys,

several methods like Worksheet.get_addr_int or Worksheet.range throw the following error:
   
  File myfile.py", line 398, in main
    except gspread.httpsession.HTTPError:
...
mycode, calling sheet.get_addr_int(headerRow,
                  sheet.col_count)
  ....

  File "/code/reco-analyses/logProcessor_maintenance/ve/local/lib/python2.7/site-packages/gspread/models.py", line 326, in range
    'return-empty': 'true'})
  File "/code/reco-analyses/logProcessor_maintenance/ve/local/lib/python2.7/site-packages/gspread/client.py", line 244, in get_cells_feed
    r = self.session.get(url)
  File "/code/reco-analyses/logProcessor_maintenance/ve/local/lib/python2.7/site-packages/gspread/httpsession.py", line 79, in get
    return self.request('GET', url, **kwargs)
  File "/code/reco-analyses/logProcessor_maintenance/ve/local/lib/python2.7/site-packages/gspread/httpsession.py", line 72, in request
    response = self.connections[uri.scheme+uri.netloc].getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1018, in getresponse
    raise ResponseNotReady()

Looks like a bug...?

**Comment by burnash** [comment]
@rmminusrslash, it looks like a network problem (HTTPError, ResponseNotReady). Could you please share a more specific code snippet?

**Comment by rmminusrslash** [comment]
@burnash 
I tried to construct a toy example but could not reproduce the exception. it turns out the reason in my original code was first catching a 500er error and retrying the request.  

I incorporated their recommended retry logic according to the docs: https://developers.google.com/drive/web/handle-errors and will see how it goes. They mention it for 403 errors but let's see if it remedies the 500er errors I keep getting. If so, could be a nice feature to add.

**Comment by gdoucet** [comment]
I do get the same error with append_row function. The script was working this morning and now I get this exception:

    wks.append_row(values)
  File "/Users/gdoucet/Library/Python/2.7/lib/python/site-packages/gspread/models.py", line 529, in append_row
    self.add_rows(1)
  File "/Users/gdoucet/Library/Python/2.7/lib/python/site-packages/gspread/models.py", line 514, in add_rows
    self.resize(rows=self.row_count + rows)
  File "/Users/gdoucet/Library/Python/2.7/lib/python/site-packages/gspread/models.py", line 495, in resize
    feed = self.client.get_feed(self_uri)
  File "/Users/gdoucet/Library/Python/2.7/lib/python/site-packages/gspread/client.py", line 245, in get_feed
    r = self.session.get(url)
  File "/Users/gdoucet/Library/Python/2.7/lib/python/site-packages/gspread/httpsession.py", line 79, in get
    return self.request('GET', url, **kwargs)
  File "/Users/gdoucet/Library/Python/2.7/lib/python/site-packages/gspread/httpsession.py", line 72, in request
    response = self.connections[uri.scheme+uri.netloc].getresponse()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1033, in getresponse
    raise ResponseNotReady()
httplib.ResponseNotReady

**Comment by burnash** [comment]
@gdoucet Could you please share a more specific code snippet?

**Comment by burnash** [comment]
@rmminusrslash thanks for sharing the docs

**Comment by gdoucet** [comment]
@burnash
I change the code a bit and I got a different exception:
Traceback (most recent call last):
  File "/Users/gdoucet/Dev/p.py", line 255, in <module>
    add_google_sheet_row(ranks, user_to_rank)
  File "/Users/gdoucet/Dev/p.py", line 202, in add_google_sheet_row
    update_user_sheet(user, rank, ranks[rank])
  File "/Users/gdoucet/Dev/p.py", line 168, in update_user_sheet
    wks.update_cell(cell.row, col, value)
  File "/Users/gdoucet/Library/Python/2.7/lib/python/site-packages/gspread/models.py", line 440, in update_cell
    self._cell_addr(row, col))
  File "/Users/gdoucet/Library/Python/2.7/lib/python/site-packages/gspread/client.py", line 262, in get_cells_cell_id_feed
    r = self.session.get(url)
  File "/Users/gdoucet/Library/Python/2.7/lib/python/site-packages/gspread/httpsession.py", line 79, in get
    return self.request('GET', url, **kwargs)
  File "/Users/gdoucet/Library/Python/2.7/lib/python/site-packages/gspread/httpsession.py", line 75, in request
    raise HTTPError(response)
gspread.httpsession.HTTPError


def setup_google():
	client_id = 'XXXXXXXX'
	client_secret = 'XXXXXXXXXX'
	scope = 'https://spreadsheets.google.com/feeds/'
	flow = OAuth2WebServerFlow(client_id, client_secret, scope)
	parser = argparse.ArgumentParser(parents=[tools.argparser])
	flags = parser.parse_args()
	storage = Storage('credentials.dat')
	credentials = storage.get()
	if credentials is None or credentials.invalid:
		credentials = tools.run_flow(flow, storage, flags)
	return credentials

def update_user_sheet(user, rank, info):
	credentials = setup_google()
	gc = gspread.authorize(credentials)
	d = datetime.datetime.now()
	current_date = d.strftime('%Y-%m-%d')
	headers = ['header1', 'header2', 'header3', 'header4']
	wks = gc.open('Sheet1').worksheet(user)
	values = []
	values.append(current_date)
	values.append(user)
	values.append(rank)
	for header in headers:
		values.append(info[header])
	try:
		cell = wks.find(current_date)
		col = 0
		for value in values:
			wks.update_cell(cell.row, col, value)
			col += 1
	except gspread.exceptions.CellNotFound:
		wks.append_row(values)

**Comment by burnash** [comment]
@gdoucet thanks for a snippet (and kudos for formatting.) The new error you're getting looks similar to the [Invalid token: Token not found](https://github.com/burnash/gspread/issues/170#issuecomment-88933723) error from the discussion in #170. Can you check if [using a different approach to oAuth](https://github.com/burnash/gspread/issues/170#issuecomment-90731740) helps in your case?

**Comment by rmminusrslash** [comment]
the error still persists. the status code before retry is 502 or occasionally 500.

'The server encountered a temporary error and could not complete your request. Please try again in 30 seconds. '

Is the 502 error gspread related or possibly an issue with the API?

    import gspread
    import random
    import json
    from oauth2client.client import SignedJwtAssertionCredentials
    
    def main():
    
        json_key = json.load(open("/home/lina/.credentials/APIProject-56725514b81f.json"))
        scope = ['https://spreadsheets.google.com/feeds']
    
        credentials = SignedJwtAssertionCredentials(json_key['client_email'], json_key['private_key'], scope)
        client = gspread.authorize(credentials)
        filename =  "Test"
        spreadsheet = client.open(filename)
        while True:
            sheet='PDS %i' %random.choice([1,2,3])
            wks = spreadsheet.worksheet(sheet)
            range= wks.range('A1:Z1')
            range[0].value = random.random()
            range[1].value = random.random()
            range[2].value = random.random()
            wks.update_cells(range)
    
    
    if __name__ == '__main__':
        main()

Stacktrace:
Traceback (most recent call last):
  File "/code/reco-analyses/logProcessor_maintenance/src_maintenance/deliver_kpis_googleDoc_TOY.py", line 32, in <module>
    
  File "/code/reco-analyses/logProcessor_maintenance/src_maintenance/deliver_kpis_googleDoc_TOY.py", line 22, in main
    range[0].value = random.random()
  File "/code/reco-analyses/logProcessor_maintenance/ve/local/lib/python2.7/site-packages/gspread/models.py", line 334, in range
    'return-empty': 'true'})
  File "/code/reco-analyses/logProcessor_maintenance/ve/local/lib/python2.7/site-packages/gspread/client.py", line 250, in get_cells_feed
    r = self.session.get(url)
  File "/code/reco-analyses/logProcessor_maintenance/ve/local/lib/python2.7/site-packages/gspread/httpsession.py", line 79, in get
    return self.request('GET', url, **kwargs)
  File "/code/reco-analyses/logProcessor_maintenance/ve/local/lib/python2.7/site-packages/gspread/httpsession.py", line 75, in request
    raise HTTPError("%s: %s" % (response.status, response.read()))
gspread.exceptions.HTTPError: 502: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 502 (Server Error)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/errors/logo_sm_2.png) no-repeat}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/errors/logo_sm_2_hr.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/errors/logo_sm_2_hr.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/errors/logo_sm_2_hr.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:55px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>502.</b> <ins>That’s an error.</ins>
  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That’s all we know.</ins>

**Comment by danio368** [comment]
Hi, 
I am facing the very same problem. append_row would sometimes work, sometimes throw this 502 error. From my observation, when the error is thrown, a new line is added to the spreadsheet, but not populated with the values. And the error is thrown.
Did you by chance find a solution or workaround ?
Any help would be very much appreciated

**Comment by msuozzo** [comment]
This is likely a Google API limit. I'm not exactly sure what this limit is but this is the likely cause.

Looking at the code segment posted by @rmminusrslash, there is API interaction in a `while True` block which is a sure sign of overuse.

@danio368, append_row is implemented as two API calls (one to create the row and another to populate it) so the blank row is likely due to the API quota being hit by the second call.

I've added a feature request (#314) for a helpful error message for this situation. Progress towards resolution of this issue can be followed there.

**Comment by rmminusrslash** [comment]
@msuozzo the example is only a toy one to allow reproducing the error ( so no "overuse" in the actual code)

@danio368  it turned out the reason was indeed a limit on the API calls, so the library is not at fault.
If you can reduce the number of calls by refactoring or use a different machine (I suspect the number of requests from our company IP's is the culprit in my case), that could help
