### ISSUE TITLE
Basic del_worksheet example doesn't work; returns HTTPError

### ISSUE THREAD

**Issue by jebstone** [burnash/gspread#219]
I'm collecting a fair bit of data in Google Spreadsheets (not by choice) and need to frequently delete records.

I can't find any way to do that; the basic del_worksheet example returns an HTTPError. Support for del_row hasn't been merged in, and there's no apparent way to reset a cell value to blank. (To top it all off, the github post preview isn't working either so I can't even check my markdown.)

I hope you can help. Here's all 5 lines of my code:

``` python
    import gspread

    gc = gspread.login('user@gmail.com','password')
    spreadsheet = gc.open("ThinMintTest")
    worksheet = spreadsheet.sheet1

    spreadsheet.del_worksheet(worksheet)
```

Here's the error:

Traceback (most recent call last):
  File "D:\tmp\test.py", line 13, in <module>
    spreadsheet.del_worksheet(worksheet)
  File "C:\Anaconda3\lib\site-packages\gspread\models.py", line 102, in del_worksheet
    self.client.del_worksheet(worksheet)
  File "C:\Anaconda3\lib\site-packages\gspread\client.py", line 251, in del_worksheet
    r = self.session.delete(url)
  File "C:\Anaconda3\lib\site-packages\gspread\httpsession.py", line 82, in delete
    return self.request('DELETE', url, **kwargs)
  File "C:\Anaconda3\lib\site-packages\gspread\httpsession.py", line 75, in request
    raise HTTPError(response)
gspread.httpsession.HTTPError: <http.client.HTTPResponse object at 0x0000000002A72DD8>
[Finished in 1.3s]

Thanks!

**Comment by burnash** [comment]
I've updated `gspread` so now it returns a message along with this exception. Can you update the library, rerun your code and post the exception message?

**Comment by jebstone** [comment]
Thank you so much for the help. The error now returns the following:

  File "C:\Anaconda3\lib\site-packages\gspread\httpsession.py", line 75, in request
    raise HTTPError("%s: %s" % (response.status, response.read()))
gspread.exceptions.HTTPError: 400: b'You can&#39;t remove the last sheet in a document.'

The error makes sense now that I can see it. I know this is rudimentary, but I'm just learning to track these things down.

In my particular use case -- trying to periodically move records from a Google Spreadsheet to a database so I can drop thousands of records a day into the spreadsheet -- it's not going to work. Deleting a spreadsheet, then creating a new one with the same name, causes my (squarespace) form to lose its connection and I have to re-establish that connection manually. I'm looking forward to seeing gspread enable a del_row() function sometime in the future.

Thanks again, I greatly appreciate your help and your gspread project.

**Comment by hvaithia** [comment]
Hi,

I get this error when I try to delete a worksheet

Traceback (most recent call last):
  File "./workSheetFunctions.py", line 54, in <module>
    deleteWorksheet("TestSpreadsheet","Sheet3")
  File "./workSheetFunctions.py", line 42, in deleteWorksheet
    sp_handler.del_worksheet(worksheet)							#worksheet deleted
  File "/usr/local/lib/python2.7/site-packages/gspread/models.py", line 103, in del_worksheet
    self._sheet_list.remove(worksheet)
ValueError: list.remove(x): x not in list

The sheet gets deleted but I get this exception.
---
code
sp_handler=gc.open("my_spreadsheet")
worksheet=sp_handler.worksheet("my_worksheet")
sp_handler.del_worksheet(worksheet)

---
Can you take a look into this. 

Btw, this project is very impressive. Thank you!

**Comment by Wrufesh** [comment]
I am also facing the same problem. Do we have any fix? Is this a bug?

**Comment by msuozzo** [comment]
I can't reproduce this error. Does anyone who is still seeing this problem have a detailed description of steps to reproduce including their Python version and OS?

Thanks.

**Comment by burnash** [comment]
I'm closing this issue for inactivity. Please feel free to reopen it if you have further input.
