### ISSUE TITLE
Connection Failed Error

### ISSUE THREAD

**Issue by daniel-geffen** [burnash/gspread#232]
I found out about gspread and it is just what I need for my code, but after I added gspread to my code, it updated a few cells before returning the following error. I tried to run the code a few more times but it still didn't work. I have a good internet connection and I can browse the web easily, but the code refuses to complete.

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 349, in _make_request
    conn.request(method, url, *_httplib_request_kw)
  File "C:\Python34\lib\http\client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1126, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 922, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 857, in send
    self.connect()
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 155, in connect
    conn = self._new_conn()
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, *_extra_kw)
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\util\connection.py", line 88, in create_connection
    raise err
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\util\connection.py", line 78, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\requests\adapters.py", line 370, in send
    timeout=timeout
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\util\retry.py", line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\packages\six.py", line 309, in reraise
    raise value.with_traceback(tb)
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 349, in _make_request
    conn.request(method, url, *_httplib_request_kw)
  File "C:\Python34\lib\http\client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1126, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 922, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 857, in send
    self.connect()
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 155, in connect
    conn = self._new_conn()
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, *_extra_kw)
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\util\connection.py", line 88, in create_connection
    raise err
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\util\connection.py", line 78, in create_connection
    sock.connect(sa)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tuvia\Documents\Python Scripts\defender distance.py", line 101, in <module>
    response1 = requests.get(url2)
  File "C:\Python34\lib\site-packages\requests\api.py", line 68, in get
    return request('get', url, *_kwargs)
  File "C:\Python34\lib\site-packages\requests\api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 465, in request
    resp = self.send(prep, *_send_kwargs)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 573, in send
    r = adapter.send(request, *_kwargs)
  File "C:\Python34\lib\site-packages\requests\adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))

**Comment by burnash** [comment]
Are you using some kind of proxy?

**Comment by dandani18** [comment]
I'm using OAuth2, as written here: http://gspread.readthedocs.org/en/latest/oauth2.html.
This is the code I use to log in:

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = "C:/Users/tuvia/Downloads/check-526c171ed8c9.json"


credentials = GoogleCredentials.get_application_default()
credentials = credentials.create_scoped(['https://spreadsheets.google.com/feeds'])

gc = gspread.authorize(credentials)

**Comment by burnash** [comment]
Good, but are you behind any proxy? Google the error: it happens in [many environments, not only in Python](https://www.google.com/search?q=%22A+connection+attempt+failed+because+the+connected+party+did+not+properly+respond+after+a+period+of+time%2C+or+established+connection+failed+because+connected+host+has+failed+to+respond%22). Which suggests that the error may be of the generic nature.

**Comment by dandani18** [comment]
I'm pretty sure I'm not behind a proxy

**Comment by msuozzo** [comment]
Has this issue persisted?

**Comment by burnash** [comment]
@daniel-geffen I'm closing this issue for inactivity. Please feel free to reopen it if you have further input.

**Comment by lidatou1991** [comment]
> @daniel-geffen I'm closing this issue for inactivity. Please feel free to reopen it if you have further input.

I am coming across the same problem. Since I am located in China so I am using network proxy.

problem description and trials in [https://stackoverflow.com/questions/56276603/timeout-error-how-to-fix-google-drive-api-for-google-spreadsheet-in-python/56297060#56297060](url)

Hope to see your help. Thanks in advance
