### ISSUE TITLE
Issue with credentials using oauth for gspread

### ISSUE THREAD

**Issue by jbresle** [burnash/gspread#238]
I apologize in advance as this is likely not a gspread issue, but I followed instructions I think you posted to use oauth2 to get into drive.

import gspread
import json
from oauth2client.client import SignedJwtAssertionCredentials

json_key = json.load(open('Test for gspread-78c678a7fb15.json'))
scope = ['https://spreadsheets.google.com/feeds']
credentials = SignedJwtAssertionCredentials(json_key['client_email'], json_key['private_key'], scope)
gc = gspread.authorize(credentials)

and I am getting the following error:

Traceback (most recent call last):
  File "<pyshell#27>", line 1, in <module>
    credentials = SignedJwtAssertionCredentials(json_key['client_email'], json_key['private_key'], scope)
  File "C:\Python33\lib\site-packages\oauth2client\util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Python33\lib\site-packages\oauth2client\client.py", line 1515, in __init__
    self.private_key = base64.b64encode(private_key)
  File "C:\Python33\lib\base64.py", line 58, in b64encode
    raise TypeError("expected bytes, not %s" % s.__class__.__name__)
TypeError: expected bytes, not str

Any ideas?

**Comment by jbresle** [comment]
I have solved this.  I used this line instead, and it worked:

credentials = SignedJwtAssertionCredentials(json_key['client_email'], str.encode(json_key['private_key']), scope)
