### ISSUE TITLE
Oauth2 problem

### ISSUE THREAD

**Issue by jifferent** [burnash/gspread#239]
I followed the instruction here: http://gspread.readthedocs.org/en/latest/oauth2.html#custom-credentials-objects

        json_key = settings.GOOGLE_CREDENTIAL
        scope = ['https://spreadsheets.google.com/feeds']
        credentials = SignedJwtAssertionCredentials(json_key['client_email'], json_key['private_key'], scope)
        gc = gspread.authorize(credentials)

Traceback (most recent call last):
  File "google_drive_api.py", line 56, in login_with_username_password
    gc = gspread.authorize(credentials)
  File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 335, in authorize
    client.login()
  File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 98, in login
    self.auth.refresh(http)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 577, in refresh
    self._refresh(http.request)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 748, in _refresh
    self._do_refresh_request(http_request)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 772, in _do_refresh_request
    body = self._generate_refresh_request_body()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 1379, in _generate_refresh_request_body
    assertion = self._generate_assertion()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 1508, in _generate_assertion
    private_key, self.private_key_password), payload)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/crypt.py", line 134, in from_string
    pkey = crypto.load_privatekey(crypto.FILETYPE_PEM, parsed_pem_key)
Error: [('PEM routines', 'PEM_read_bio', 'bad base64 decode')]

I am using python 2.7.3

Ang idea?

**Comment by mitnk** [comment]
Does you "private_key" contain `\u003d` (aka `=`) chars? I encountered the same issue. Regenerate new credentials until it doesn't include `\u003d`. Then it should be fine. Not sure who is the owner of the bug :)

**Comment by felagund** [comment]
Thanks, the solution with regenerating keys worked (I would say this is https://github.com/google/oauth2client problem).

**Comment by felagund** [comment]
I reported it there: https://github.com/google/oauth2client/issues/192

**Comment by jifferent** [comment]
@mitnk

Thanks, my private_key does contain \u003d, but I regenerate 17 times, it still contains it. it is because a bad luck or there is trick to do it?

**Comment by jifferent** [comment]
Okay, I delete my key and create a new key, it finally does not contain "\u003d"

Thank you @mitnk

**Comment by felagund** [comment]
BTW: as per https://github.com/google/oauth2client/issues/192 one needs to encode the key that contains `'u003d'`like this: `key = u'-----BEGIN PRIVATE KEY-----blabla\\u003d\n-----END PRIVATE KEY-----\n'.encode('utf8')
