### ISSUE TITLE
add_rows throws errors

### ISSUE THREAD

**Issue by djiddish98** [burnash/gspread#240]
So like a few users, I had to update my code today to login via OAuth. I also made sure to update my gspread (which was previously done probably around last November).

That process appears to have been relatively smooth, thanks to your great instructions. I can atleast see that the code is reading values from the spreadsheet in question.

However, when my code attempts to call add_rows, it blows up.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Maheitz\AppData\Local\Continuum\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 580, in runfile
    execfile(filename, namespace)
  File "C:/Users/Maheitz/Google Drive/Python/updateExperimentData.py", line 117, in <module>
    wks.add_rows(n) 
  File "c:\runs\gspread-master\gspread\models.py", line 514, in add_rows
    self.resize(rows=self.row_count + rows)
  File "c:\runs\gspread-master\gspread\models.py", line 507, in resize
    self._element = self.client.put_feed(uri, ElementTree.tostring(feed))
  File "c:\runs\gspread-master\gspread\client.py", line 282, in put_feed
    if ex.code == 403:
AttributeError: 'HTTPError' object has no attribute 'code'

Any help would be greatly appreciated! Thanks again for this wonerful tool.

**Comment by djiddish98** [comment]
Quick update: 

I tweaked the code in line 282 of client.py to look more like this:

https://github.com/burnash/gspread/commit/74ac089e526b76a1d6e6ae24e86aafaeec8e3af9

and now get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Maheitz\AppData\Local\Continuum\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 580, in runfile
    execfile(filename, namespace)
  File "C:/Users/Maheitz/Google Drive/Python/updateExperimentData.py", line 117, in <module>
    wks.add_rows(n) 
  File "c:\runs\gspread-master\gspread\models.py", line 514, in add_rows
    self.resize(rows=self.row_count + rows)
  File "c:\runs\gspread-master\gspread\models.py", line 507, in resize
    self._element = self.client.put_feed(uri, ElementTree.tostring(feed))
  File "c:\runs\gspread-master\gspread\client.py", line 286, in put_feed
    raise ex
gspread.exceptions.HTTPError: 400: The reference to entity &quot;format&quot; must end with the &#39;;&#39; delimiter.

**Comment by djiddish98** [comment]
Ah, I think I found the problem -- I had previously locked this tab so only I could edit it (with my old login email). 

I'd probably have to approve myOAuth email to also edit for the add_rows to work...I ended up just removing the locking feature and things seem to be ok.

Thanks!

**Comment by burnash** [comment]
Great, thanks for posting the issue
