### ISSUE TITLE
Getting Error xml.etree.ElementTree.ParseError: mismatched tag: line 2, column 26

### ISSUE THREAD

**Issue by yizhouw** [burnash/gspread#245]
I used the following code to login:

json_key = json.load(open('credential.txt'))
    scope = ['https://spreadsheets.google.com/feeds']
    credentials = SignedJwtAssertionCredentials(json_key['client_email'], json_key['private_key'], scope)
    gc = gspread.authorize(credentials)

And tried to use 

agent = log_in(user_name, password)
                    wks = agent.open(FileName).worksheet('Benchmark_Region')

to open a worksheet. 

Getting error as:

Traceback (most recent call last):
  File "/Users/yizhou/Documents/workspace/UberReport/RGM/GSpreadsheet.py", line 272, in <module>
    run(report_date,pw)
  File "/Users/yizhou/Documents/workspace/UberReport/RGM/GSpreadsheet.py", line 254, in run
    update_city_management('asdf','asdf',FileName,'Completed_Trips',2,6)
  File "/Users/yizhou/Documents/workspace/UberReport/RGM/GSpreadsheet.py", line 110, in update_city_management
    wks = agent.open(FileName).worksheet('City Management')
  File "/users/yizhou/anaconda/lib/python2.7/site-packages/gspread/client.py", line 143, in open
    feed = self.get_spreadsheets_feed()
  File "/users/yizhou/anaconda/lib/python2.7/site-packages/gspread/client.py", line 230, in get_spreadsheets_feed
    return ElementTree.fromstring(r.read())
  File "/users/yizhou/anaconda/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/users/yizhou/anaconda/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/users/yizhou/anaconda/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: mismatched tag: line 2, column 26

**Comment by burnash** [comment]
What do you need this for?
```python
agent = log_in(user_name, password)
```

**Comment by YeisonVargas** [comment]
Hi, I have a similar problem, "xml.etree.ElementTree.ParseError: no element found" , 

` import json`
`import gspread`
`from oauth2client.client import SignedJwtAssertionCredentials`

`json_key = json.load(open('corizapp-2245ac6c6918.json'))`
`scope = ['https://spreadsheets.google.com/feeds/']`
`credentials = SignedJwtAssertionCredentials(json_key['client_email'], bytes(json_key['private_key'], 'utf-8'), scope)`
`obj = gspread.authorize(credentials)`
`my_sheet = obj.open("pinks").sheet1`

The traceback is:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/gspread/client.py", line 134, in open
    feed = self.get_spreadsheets_feed()
  File "/usr/local/lib/python3.4/dist-packages/gspread/client.py", line 220, in get_spreadsheets_feed
    return ElementTree.fromstring(r.read())
  File "/usr/lib/python3.4/xml/etree/ElementTree.py", line 1326, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

Python version: 3.4
gspread version: 0.2.3

URL in method 'get_spreadsheets_feed()' is diferent to https://spreadsheets.google.com/feeds/spreadsheets/, I am printing the r variable:

`print(r.read())`

Seems that the r variable doesn't save all the XML from https://spreadsheets.google.com/feeds/spreadsheets/private/full 

I hope that help me!
Thanks! :+1:

**Comment by msuozzo** [comment]
> Seems that the r variable doesn't save all the XML

Can you elaborate on this? What is the output of the `print(r.read())`?

**Comment by burnash** [comment]
I'm closing this issue for inactivity. Please feel free to reopen it if you have further input.
