### ISSUE TITLE
Problems after oAuth credentials change.

### ISSUE THREAD

**Issue by cheew** [burnash/gspread#250]
Hi, Firstly I would like to say thanks for your API, It has made It so easy for me (A beginner in linux) to achieve what I have been trying to achieve. (Remote temperature monitoring with RPi)

Unfortunately, since Google changed to the oAuth2 credentials I have been having problems with my code.

I have been able to run my code and authenticate, and my spreadsheet has updated, but it is very hit and miss. Now I am getting the error below when I run the code from my raspberry Pi (Raspian) or from my Linux mint Laptop.

~~~python 
matthew@linux ~/Downloads $ python templog1.py
Traceback (most recent call last):
  File "templog1.py", line 35, in <module>
    worksheet.append_row(values)
  File "/usr/local/lib/python2.7/dist-packages/gspread/models.py", line 529, in append_row
    self.add_rows(1)
  File "/usr/local/lib/python2.7/dist-packages/gspread/models.py", line 514, in add_rows
    self.resize(rows=self.row_count + rows)
  File "/usr/local/lib/python2.7/dist-packages/gspread/models.py", line 507, in resize
    self._element = self.client.put_feed(uri, ElementTree.tostring(feed))
  File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 280, in put_feed
    r = self.session.put(url, data, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/gspread/httpsession.py", line 88, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gspread/httpsession.py", line 72, in request
    response = self.connections[uri.scheme + uri.netloc].getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
~~~

I have no idea where i'm going wrong as one minute it was working and the next it is not without any changes.

Any ideas will be welcome.
Mat.

**Comment by cheew** [comment]
I am able to run the code from home on my broadband it turns out,but not through my static IP 3g dongle.
The change acell function works, but the append_row() always returns the above error on the 3g dongle. append_row(values) is working fine from homeon the broadband now. :S

I'm starting to think it might be a timing problem with the network.

**Comment by burnash** [comment]
Sorry for the late reply. Yes, it could be timing, and Google could drop long running connections. Did you try to measure how long it takes your script to append row on that 3g connection?

**Comment by msuozzo** [comment]
This is caused by the connection being reset. The current solution is to reauthorize gspread after each one of these errors.

The future solution is to make this reauthorization seamless which will be discussed/developed in #302.
