### ISSUE TITLE
`gspread.authorize()` fails with OAuth2 client key error

### ISSUE THREAD

**Issue by sr-murthy** [burnash/gspread#266]
In my Google Developers Console account I have created OAuth 2.0 credentials for a Google spreadsheets client I am writing using the `gspread` library - I create the client using `gspread.authorize(OAuth_credentials)` where

```
OAuth2_credentials = SignedJwtAssertionCredentials(
  client_email,
  client_private_key,
  client_auth_scope
)
```

is the OAuth 2.0 credentials I created.  But I get the following error:

```
Traceback (most recent call last):
File "<console>", line 1, in <module>
File "/usr/local/lib/python2.6/dist-packages/gspread/client.py", line 335, in authorize
  client.login()
File "/usr/local/lib/python2.6/dist-packages/gspread/client.py", line 98, in login
  self.auth.refresh(http)
File "/usr/local/lib/python2.6/dist-packages/oauth2client/client.py", line 598, in refresh
  self._refresh(http.request)
File "/usr/local/lib/python2.6/dist-packages/oauth2client/client.py", line 769, in _refresh
  self._do_refresh_request(http_request)
File "/usr/local/lib/python2.6/dist-packages/oauth2client/client.py", line 795, in _do_refresh_request
  body = self._generate_refresh_request_body()
File "/usr/local/lib/python2.6/dist-packages/oauth2client/client.py", line 1425, in _generate_refresh_request_body
  assertion = self._generate_assertion()
File "/usr/local/lib/python2.6/dist-packages/oauth2client/client.py", line 1554, in _generate_assertion
  private_key, self.private_key_password), payload)
File "/usr/local/lib/python2.6/dist-packages/oauth2client/crypt.py", line 300, in from_string
  pkey = RSA.importKey(parsed_pem_key)
File "/usr/local/lib/python2.6/dist-packages/Crypto/PublicKey/RSA.py", line 638, in importKey
  if lines[1].startswith(b('Proc-Type:4,ENCRYPTED')):
IndexError: list index out of range
```

**Comment by msuozzo** [comment]
So from the stack trace, it looks like the oauth2client was expecting an RSA key string with linebreaks but it didn't find any. Are you sure you're using the exact string from the JSON file you downloaded? Do you load the key using the code provided in the [OAuth page](http://gspread.readthedocs.org/en/latest/oauth2.html) of the docs?

**Comment by burnash** [comment]
@sr-murthy I'm closing this issue for inactivity. Please feel free to reopen it if you have further input.
