### ISSUE TITLE
httplib2 ServerNotFoundError

### ISSUE THREAD

**Issue by carowjp** [burnash/gspread#322]
I am running on Win7 behind a firewall. I have HTTP_PROXY and HTTPS_PROXY system variables set. I can successfully use gspread when running my python code from the command line or an editor (spyder).  However, when the python code is invoked by another program (modeFrontier) I receive the following error : "httplib2.ServerNotFoundError: Unable to find the server at accounts.google.com".

I suspect something related to the proxy but don't know how to specify in code that httplib2 use a specific proxy.

Thanks for your work on the API, it is very useful.

regards, Jim

Full trace below...

~~~
Traceback (most recent call last):
  File "C:\Users\CAROWJP\AppData\Local\Temp\9a5fb34d-1bc5-46be-84f9-e2bb631fc7ce\pythonScript114364033034535996.py", line 25, in <module>
    exec(compile(open('C:\Users\CAROWJP\Desktop\Python\gspreadDemo.py').read(),'C:\Users\CAROWJP\Desktop\Python\gspreadDemo.py','exec'))
  File "C:\Users\CAROWJP\Desktop\Python\gspreadDemo.py", line 37, in <module>
    gc = gspread.authorize(credentials)
  File "build\bdist.win-amd64\egg\gspread\client.py", line 331, in authorize
  File "build\bdist.win-amd64\egg\gspread\client.py", line 101, in login
  File "build\bdist.win-amd64\egg\oauth2client\client.py", line 633, in refresh
  File "build\bdist.win-amd64\egg\oauth2client\client.py", line 842, in _refresh
  File "build\bdist.win-amd64\egg\oauth2client\client.py", line 874, in _do_refresh_request
  File "C:\Users\CAROWJP\AppData\Local\Continuum\Anaconda\lib\site-packages\httplib2__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "C:\Users\CAROWJP\AppData\Local\Continuum\Anaconda\lib\site-packages\httplib2__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Users\CAROWJP\AppData\Local\Continuum\Anaconda\lib\site-packages\httplib2__init__.py", line 1278, in _conn_request
    raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
httplib2.ServerNotFoundError: Unable to find the server at accounts.google.com
~~~

**Comment by lavigne958** [comment]
Unfortunately can't test this scenario easily, no update for many years, closing this issue. If it is still not working let me know here we will investigate.
