### ISSUE TITLE
oauth2client.client.AccessTokenRefreshError: invalid_grant

### ISSUE THREAD

**Issue by theseatoms** [burnash/gspread#327]
I followed the directions prescribed here:

http://gspread.readthedocs.org/en/latest/oauth2.html

And received the following error:

Traceback (most recent call last):
  File "tweet.py", line 87, in <module>
    gspread_client = gspread.authorize(credentials)
  File "/Users/theseatoms/mc/twtr/project/env/lib/python2.7/site-packages/gspread/client.py", line 335, in authorize
    client.login()
  File "/Users/theseatoms/mc/twtr/project/env/lib/python2.7/site-packages/gspread/client.py", line 98, in login
    self.auth.refresh(http)
  File "/Users/theseatoms/mc/twtr/project/env/lib/python2.7/site-packages/oauth2client/client.py", line 626, in refresh
    self._refresh(http.request)
  File "/Users/theseatoms/mc/twtr/project/env/lib/python2.7/site-packages/oauth2client/client.py", line 835, in _refresh
    self._do_refresh_request(http_request)
  File "/Users/theseatoms/mc/twtr/project/env/lib/python2.7/site-packages/oauth2client/client.py", line 900, in _do_refresh_request
    raise AccessTokenRefreshError(error_msg)
oauth2client.client.AccessTokenRefreshError: invalid_grant

I've shared the spreadsheet with the email found within the json credentials file at json_key['client_email'].

Here's a code snippet, taken almost exactly from the aforementioned site.

 82 oauthfile = 'service_accnt_new.json'
 83 scope = ['https://spreadsheets.google.com/feeds']
 84 json_key = json.load(open(oauthfile))
 85 credentials = SignedJwtAssertionCredentials(json_key['client_email'], json_key['private_key'].encode(), scope)
 86
 87 gspread_client = gspread.authorize(credentials)

My program only needs to access and read my own spreadsheets.

**Comment by msuozzo** [comment]
Two things come to mind:

* Make sure you're using a Client ID created as a "Service Account" (Step 4)
* Make sure you've enabled the Drive API in the "APIs & Auth" section of Google Developers Console.

If neither of those checks work and you're unable to determine the cause of this issue, please provide your platform and any other circumstantial information that might be helpful.

Thanks for reporting your issue :)

**Comment by theseatoms** [comment]
Re-creating my credentials json file solved my issue.

Thanks for your speedy response.

**Comment by msuozzo** [comment]
Glad everything worked out :+1:
