### ISSUE TITLE
OpenSSL.crypto.Error: []

### ISSUE THREAD

**Issue by carlobailey** [burnash/gspread#340]
I'm using Linux (Raspbian) and I've followed the steps [here](http://gspread.readthedocs.org/en/latest/oauth2.html), and installed PyOpenSSL as recommended by others. I am using gspread with SignedJwtAssertionCredentials and keeping getting the following error:

Traceback (most recent call last):
  File "logger.py", line 60, in <module>
    worksheet = login_open_sheet(GDOCS_OAUTH_JSON, GDOCS_SPREADSHEET_NAME)
  File "logger.py", line 45, in login_open_sheet
    gc = gspread.authorize(credentials)
  File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 331, in authorize
    client.login()
  File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 101, in login
    self.auth.refresh(http)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 633, in refresh
    self._refresh(http.request)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 842, in _refresh
    self._do_refresh_request(http_request)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 869, in _do_refresh_request
    body = self._generate_refresh_request_body()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 1549, in _generate_refresh_request_body
    assertion = self._generate_assertion()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 1677, in _generate_assertion
    private_key, self.private_key_password), payload)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/_openssl_crypt.py", line 117, in from_string
    pkey = crypto.load_privatekey(crypto.FILETYPE_PEM, parsed_pem_key)
OpenSSL.crypto.Error: [('PEM routines', 'PEM_read_bio', 'no start line')]

Thanks for the help!

**Comment by carlobailey** [comment]
I figured it out.
It was an issue with how the private key was encoded - I followed the suggestions [here](https://github.com/google/oauth2client/issues/192) to resolve.
