### ISSUE TITLE
Error Raised when trying to del_worksheet

### ISSUE THREAD

**Issue by dbradleyb67** [burnash/gspread#344]
HEre is the Arror that I get when I try to delete a worksheet:

Traceback (most recent call last):
  File "Addsheets2icat.py", line 33, in <module>
    worksheet = wks.del_worksheet(sheetname)
  File "C:\Users\David\Anaconda\lib\site-packages\gspread\models.py", line 102,
in del_worksheet
    self.client.del_worksheet(worksheet)
  File "C:\Users\David\Anaconda\lib\site-packages\gspread\client.py", line 259,
in del_worksheet
    'worksheet', worksheet, 'private', 'full', worksheet_version=worksheet.versi
on)
AttributeError: 'str' object has no attribute 'version'

**Comment by ptiger10** [comment]
Have you found any resolution to this? I haven't found an alternative for clearing a worksheet beyond deleting and recreating, so this error is problematic.

**Comment by dbradleyb67** [comment]
Still no resolution for this issue.

**Comment by miike** [comment]
If you're seeing the following error "UrlParameterMissing: 'version'" or similar (or version is None) ensure that the user you are authenticating as has edit permission on the worksheet.

**Comment by dbradleyb67** [comment]
The user has edit permissions on the document.  the user can update cells in the document

**Comment by duncangh** [comment]
Just to follow up, is a resolution at large for this issue?

**Comment by ryantuck** [comment]
you may be attempting to pass in the worksheet name instead of the `worksheet` object.

```python
# this should work
sheet = sh.worksheet('test')
sh.del_worksheet(sheet)

# this will not
sh.del_worksheet('test')
```

**Comment by burnash** [comment]
@dbradleyb67 did @ryantuck suggestion help you?

**Comment by burnash** [comment]
I'm closing this issue due to inactivity. Feel free to reopen it if you have an update.
