### ISSUE TITLE
TypeError: POST data... with urllib

### ISSUE THREAD

**Issue by alchenist** [burnash/gspread#35]
I'm getting this traceback when attempting to use this in Python 3.2.3, and I'm not exactly sure what to do:

``` python
>>> gc = gspread.login(email,password)
Traceback (most recent call last):
  File "<pyshell#11>", line 1, in <module>
    gc = gspread.login(email,password)
  File "C:\Python32\lib\site-packages\gspread-0.0.12-py3.2.egg\gspread\client.py", line 273, in login
    client.login()
  File "C:\Python32\lib\site-packages\gspread-0.0.12-py3.2.egg\gspread\client.py", line 82, in login
    r = self.session.post(url, data)
  File "C:\Python32\lib\site-packages\gspread-0.0.12-py3.2.egg\gspread\httpsession.py", line 65, in post
    return self.request('post', url, data=data, **kwargs)
  File "C:\Python32\lib\site-packages\gspread-0.0.12-py3.2.egg\gspread\httpsession.py", line 57, in request
    return request.urlopen(req)
  File "C:\Python32\lib\urllib\request.py", line 138, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python32\lib\urllib\request.py", line 367, in open
    req = meth(req)
  File "C:\Python32\lib\urllib\request.py", line 1065, in do_request_
    raise TypeError("POST data should be bytes"
TypeError: POST data should be bytes or an iterable of bytes. It cannot be str.
```

**Comment by DAR6969** [comment]
File "client3.py", line 42, in <module>
    quotes = json.loads(urllib.request.urlopen(Query, format(random.random())).read(
))
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 522, in open
    req = meth(req)
  File "/usr/lib/python3.8/urllib/request.py", line 1250, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes, an iterable of bytes, or a file object. It can
not be of type str.

**What do to about such an error, please help?**
