### ISSUE TITLE
fail to write to google sheet occasionally

### ISSUE THREAD

**Issue by glynnelson** [burnash/gspread#351]
I am trying to write to a sheet every 2 minutes, for which my code does work.  However, every now and again I get the error shown below.  I tried moving the google login into the readout loop, in case it was some sort of timeout in the google authorisation, but this still occasionally happens.  The instance below had successfully reported to google 19 times before giving this fail.  It must have logged in okay,a s that didn't produce an error- it seems to be the writing.  I don't understand why it fails every now and then.

The internet access for the hardware seems fine- in fact I am running the code via ssh from another machine.  I can provide the python script too if necessary.

Traceback (most recent call last):
  File "pi_tempsensor2.py", line 79, in <module>
    worksheet.append_row(values) #write to the spreadsheet
  File "build/bdist.linux-armv6l/egg/gspread/models.py", line 533, in append_row
  File "build/bdist.linux-armv6l/egg/gspread/models.py", line 328, in cell
  File "build/bdist.linux-armv6l/egg/gspread/client.py", line 269, in get_cells_cell_id_feed
  File "build/bdist.linux-armv6l/egg/gspread/httpsession.py", line 75, in get
  File "build/bdist.linux-armv6l/egg/gspread/httpsession.py", line 67, in request
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 60, in get
    return request('get', url, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))

**Comment by burnash** [comment]
Possibly similar to http://stackoverflow.com/questions/23777121/why-am-i-getting-socket-gaierror-errno-2-from-python-httplib

Have you been able to resolve the issue? I'm closing the ticket for now. If the issue persists, please feel free to reopen the ticket.
