### ISSUE TITLE
unable to import gspread in fabric

### ISSUE THREAD

**Issue by liaogz82** [burnash/gspread#355]
Hi, I am unable to import gspread. This is the error I get

```
Gangzhengs-MacBook-Pro:Fabric mosesliao$ pip install gspread
Collecting gspread
Requirement already satisfied (use --upgrade to upgrade): requests>=2.2.1 in /usr/local/lib/python2.7/site-packages (from gspread)
Installing collected packages: gspread
Successfully installed gspread-0.3.0
Gangzhengs-MacBook-Pro:Fabric mosesliao$ fab google_docs
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/fabric/main.py", line 658, in main
    docstring, callables, default = load_fabfile(fabfile)
  File "/Library/Python/2.7/site-packages/fabric/main.py", line 165, in load_fabfile
    imported = importer(os.path.splitext(fabfile)[0])
  File "/Users/mosesliao/svn/chubi-trunk-project/Fabric/fabfile.py", line 29, in <module>
    import gspread
ImportError: No module named gspread
Gangzhengs-MacBook-Pro:Fabric mosesliao$ pip install gspread
Requirement already satisfied (use --upgrade to upgrade): gspread in /usr/local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): requests>=2.2.1 in /usr/local/lib/python2.7/site-packages (from gspread)
Gangzhengs-MacBook-Pro:Fabric mosesliao$ python -V
Python 2.7.11
```

**Comment by burnash** [comment]
I don't think this issue is related to gspread. My guess is that you have two Python interpreters / environments for `pip` and `fab`. Try running `which pip` and `which fab` to make sure they are using the same Python interpreter.
