### ISSUE TITLE
gspread / OAuth2client Service Account Key.

### ISSUE THREAD

**Issue by jsimeroth** [burnash/gspread#405]
I am trying to use a google Service Account Key, Other, json file to continually update a google spread sheet with gspread. It works for one hour (the lifespan of the token) then stops. The token does not refresh. I could really use an exact example of how to get my script to always run. The google OAuth2 code is as follows, and I have tried a few different variations. Any help would be greatly appreciated, thank you.

    import gspread
    from oauth2client.service_account import ServiceAccountCredentials
    import httplib2
    from httplib2 import Http

    scope = ['https://spreadsheets.google.com/feeds']
    credentials = ServiceAccountCredentials.from_json_keyfile_name(filename.json,scope)
    gc = gspread.authorize(credentials)
    wks = gc.open('spreadsheet name')
    p1 = wks.worksheet('Printer One')

    def functon()
    ....
    p1.append_row(printing)

**Comment by burnash** [comment]
What stacktrace do you get when it stops after one hour? What version of gspread are you using? More environment info would be helpful. See [ISSUE_TEMPLATE](https://github.com/burnash/gspread/blob/master/ISSUE_TEMPLATE.md).

**Comment by jsimeroth** [comment]
@burnash Thank you for your response. I am running this off a raspberry pi, with the latest version of Rapbian Jessie. My versions of gspread should be the latest, I installed it using the terminal pip command a few day ago, and tried updated. the error message I get back is "Invalid token: Statless token expired error".  I believe the my token is not refreshing like it should, but I'm not sure how to get it to refresh.

**Comment by jsimeroth** [comment]
Hello @burnash Still having the issue, this is the Tracback i get.

`Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/pins.py", line 37, in run
    if self.todo() is False:
  File "/usr/local/lib/python2.7/dist-packages/explorerhat.py", line 561, in _watch
    self._handler(self, value)
  File "/home/pi/Desktop/Mimaki Printing Sensors.py", line 54, in pin_Two
    wks = gc.open('Printer Status')
  File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 81, in open
    feed = self.get_spreadsheets_feed()
  File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 165, in get_spreadsheets_feed
    r = self.session.get(url)
  File "/usr/local/lib/python2.7/dist-packages/gspread/httpsession.py", line 76, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gspread/httpsession.py", line 72, in request
    response.status_code, response.content))
HTTPError: 401: <HTML>
<HEAD>
<TITLE>Token invalid - Invalid token: Stateless token expired</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Token invalid - Invalid token: Stateless token expired</H1>
<H2>Error 401</H2>
</BODY>
</HTML>
`

**Comment by maheshgaya** [comment]
You could add "Keep Alive" headers to increase the lifespan. 
Example:
headers = gspread.httpsession.HTTPSession(headers={'Connection': 'Keep-Alive'}) 
gc = gspread.Client(auth=credentials, http_session=headers)
gc.login()

**Comment by mateuszdrwal** [comment]
the way i got around this problem is by just refreshing all the gspread stuff every hour in a separate thread

```
import threading,time
def gspreadUpdater():
    global scope,gc,wks,p1
    while True:
        credentials = ServiceAccountCredentials.from_json_keyfile_name(filename.json,scope)
        gc = gspread.authorize(credentials)
        wks = gc.open('spreadsheet name')
        p1 = wks.worksheet('Printer One')
        time.sleep(3590)

gsUpdateThread = threading.Thread(target=gspreadUpdater)
gsUpdateThread.daemon = True
gsUpdateThread.start()
```

**Comment by davemachado** [comment]
You can also just call your `openSpreadSheet` function every X iterations. For example, while updating my sheets, I have a `if (iteration % 100 == 0): openSS()` conditional and I don't run into any more problems with auth expiring.

**Comment by jumblies** [comment]
I wanted to say thanks to the people in this thread.  

Although this may be excessive, I put the following code to upload every 
3 minutes and so far have 24 hours without a timeout.  I was getting exactly 60 minutes of successful data loggin before introducing what I gleaned from this thread.  


if (n % 3 == 0):
        # RE-Authorization and initialization of gspread
        scope = ['https://spreadsheets.google.com/feeds']
        credentials = ServiceAccountCredentials.from_json_keyfile_name('My Project.json', scope)
        gc = gspread.authorize(credentials)
        wks = gc.open("logger").sheet1
        headers = gspread.httpsession.HTTPSession(headers={'Connection': 'Keep-Alive'})
        gc = gspread.Client(auth=credentials, http_session=headers)
        gc.login()

**Comment by enod** [comment]
@jumblies Hi there. What is n in your code? Do you encounter any problem so far?

**Comment by glamke** [comment]
That's a good question.  I'm readin serial input every minute and at that point in development, I was uploading every three minutes.  I extended that to ten minutes.

**Comment by jumblies** [comment]
That's a good question. I'm reading serial input every minute and at that point in development, I was uploading every three minutes. I extended that to ten minutes.  It was working fire several weeks until I took it out of service.

**Comment by Noumanmufc1** [comment]
Hi @jumblies  Can you tell me exactly how you did it?  Like what is n here and how does it increments and stuff?

**Comment by Noumanmufc1** [comment]
@davemachado  Can you give my snippet of a code that does how you are saying?

**Comment by davemachado** [comment]
@Noumanmufc1 
```
for idx, row in enumerate(rows_i_want_to_work_with):
    # every 10th iteration, get a new connection to Google 
    # i.e. don't let current one expire
    if (idx % 10 == 0):
        reAuthToGoogle()
    # otherwise, just do your work
    do_work()
```
In this _very_ basic example, 10 is not a magic number - just reauthorize yourself to Google every so often before your current session expires.
