### ISSUE TITLE
TypeError: a float is required

### ISSUE THREAD

**Issue by henry921630** [burnash/gspread#424]
Hi,
I just built a new file for testing, here is my code:
```
import gspread
from oauth2client.service_account import ServiceAccountCredentials

def auth_gss_client(path, scopes):
    credentials = ServiceAccountCredentials.from_json_keyfile_name(path,
                                                                   scopes)
    return gspread.authorize(credentials)

auth_json_path = 'BBMouseBOT-0924da91a485.json'
gss_scopes = ['https://spreadsheets.google.com/feeds']

gss_client = auth_gss_client(auth_json_path, gss_scopes)

```
 it will show these error messages:

```
>>> 
==== RESTART: C:\Users\ext_henryy\Documents\GitHub\BBMouseBot\GStest2.py ====

Traceback (most recent call last):
  File "C:\Users\ext_henryy\Documents\GitHub\BBMouseBot\GStest2.py", line 13, in <module>
    gss_client = auth_gss_client(auth_json_path, gss_scopes)
  File "C:\Users\ext_henryy\Documents\GitHub\BBMouseBot\GStest2.py", line 8, in auth_gss_client
    return gspread.authorize(credentials)
  File "D:\python 2.7\lib\site-packages\gspread\client.py", line 293, in authorize
    client.login()
  File "D:\python 2.7\lib\site-packages\gspread\client.py", line 66, in login
    self.auth.refresh(http)
  File "D:\python 2.7\lib\site-packages\oauth2client\client.py", line 541, in refresh
    self._refresh(http)
  File "D:\python 2.7\lib\site-packages\oauth2client\client.py", line 744, in _refresh
    self._do_refresh_request(http)
  File "D:\python 2.7\lib\site-packages\oauth2client\client.py", line 775, in _do_refresh_request
    body=body, headers=headers)
  File "D:\python 2.7\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "D:\python 2.7\python-rest-client\httplib2\__init__.py", line 1050, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "D:\python 2.7\python-rest-client\httplib2\__init__.py", line 854, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "D:\python 2.7\python-rest-client\httplib2\__init__.py", line 823, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "D:\python 2.7\lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "D:\python 2.7\lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "D:\python 2.7\lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "D:\python 2.7\lib\httplib.py", line 897, in _send_output
    self.send(msg)
  File "D:\python 2.7\lib\httplib.py", line 859, in send
    self.connect()
  File "D:\python 2.7\python-rest-client\httplib2\__init__.py", line 736, in connect
    sock.settimeout(self.timeout)
  File "D:\python 2.7\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
TypeError: a float is required
>>> 
```

I've tried hard to find out what's wrong but in vain.
Could you help me?

Many thanks!

**Comment by burnash** [comment]
From the traceback it looks like the problem is coming not from gspread, but from oauth2client. It also looks like there is some misconfiguration of the environment. I'm no expert in Python on Windows but you have httplib2 in "D:\python 2.7\python-rest-client" and oauth2client in "D:\python 2.7\lib\site-packages". This looks strange to me and it could be that library versions mismatch is what causing the error.

I suggest starting from scratch with a clean environment. In instance, using [virtualenv](https://virtualenv.pypa.io/en/stable/).

**Comment by henry921630** [comment]
Thank you very much,
I'll try it again.

**Comment by burnash** [comment]
Any updates on this? Is it works now?

**Comment by burnash** [comment]
I'm closing this issue due to inactivity. Please feel free to reopen it if you have further input.

**Comment by jlaw9** [comment]
Hi, I'm getting a similar error so I think I'll comment here. I just ran through the instructions on the [python quickstart](https://developers.google.com/sheets/api/quickstart/python), and on the `credentials = tools.run_flow(flow, store, flags)` line, I'm getting the following error:

``` python
<oauth2client.client.OAuth2WebServerFlow object at 0x7f25e7c95610> <oauth2client.file.Storage object at 0x7f25e7cfa750> Namespace(auth_host_name='localhost', auth_host_port=[8080, 8090], logging_level='ERROR', noauth_local_webserver=False)

Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fspreadsheets.readonly&redirect_uri=http%3A%2F%2Flocalhost%3A8090%2F&response_type=code&client_id=297493907160-2mq4235a82adc7il5dbfpnjd9buu8ima.apps.googleusercontent.com&access_type=offline

If your browser is on a different machine then exit and re-run this
application with the command-line parameter

  --noauth_local_webserver

Created new window in existing browser session.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jeffl/Dropbox/learning/python/budgets/quickstart.py", line 63, in main
    credentials = get_credentials()
  File "/home/jeffl/Dropbox/learning/python/budgets/quickstart.py", line 49, in get_credentials
    credentials = tools.run_flow(flow, store, flags)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/tools.py", line 242, in run_flow
    credential = flow.step2_exchange(code, http=http)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 2047, in step2_exchange
    http, self.token_uri, method='POST', body=body, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/home/jeffl/.local/lib/python2.7/site-packages/httplib2/__init__.py", line 1050, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/jeffl/.local/lib/python2.7/site-packages/httplib2/__init__.py", line 854, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/jeffl/.local/lib/python2.7/site-packages/httplib2/__init__.py", line 823, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/home/jeffl/.local/lib/python2.7/site-packages/httplib2/__init__.py", line 736, in connect
    sock.settimeout(self.timeout)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
TypeError: a float is required
```

httplib2 is up to date. I can't figure out what's wrong. Any ideas?
Thanks!

**Comment by Fematich** [comment]
Hi  @jlaw9. I had the same issues with ```httplib2==0.10.3```
downgrading this to ```httplib2==0.9.2``` resolved my issues!

**Comment by jlaw9** [comment]
Thanks @Fematich!

**Comment by vj-09** [comment]
Hi team, I'm facing a similar issue even after downgrading httplib2.
