### ISSUE TITLE
SSL error when using clear or delete_row

### ISSUE THREAD

**Issue by helgisteinar** [burnash/gspread#425]
**SSL Error.**
When trying to use the `delete_row` a SSL error is eventually issued.
The same happens when using the `clear()` command.

### Environment info
Operating System: OSX
Python version: 2.7.10
gspread version: 0.5.0

### Steps to reproduce
1. Have a sheet with 150 rows and 12 columns
2. Want to delete 4 rows (next data set only has 146 rows)
3. Code is making the call, but then a SSL error is issued
4. Current workaround is to update the cells to blank

### Stack trace or other output that would be helpful
```
Traceback (most recent call last):
  File "ref_an.py", line 247, in <module>
    run_ref_an_II()
  File "ref_an.py", line 232, in run_ref_an_II
    update_sheet(G_sch,'Location',data)
  File "ref_an.py", line 218, in update_sheet
    worksheet.delete_row(x)
  File "/Users/hans/Documents/workspace/nobo_python/env/lib/python2.7/site-packages/gspread/models.py", line 600, in delete_row
    self.update_cells(cells_after_delete)
  File "/Users/hans/Documents/workspace/nobo_python/env/lib/python2.7/site-packages/gspread/models.py", line 481, in update_cells
    self.client.post_cells(self, ElementTree.tostring(feed))
  File "/Users/hans/Documents/workspace/nobo_python/env/lib/python2.7/site-packages/gspread/client.py", line 247, in post_cells
    r = self.session.post(url, data, headers=headers)
  File "/Users/hans/Documents/workspace/nobo_python/env/lib/python2.7/site-packages/gspread/httpsession.py", line 82, in post
    return self.request('POST', url, data=data, headers=headers)
  File "/Users/hans/Documents/workspace/nobo_python/env/lib/python2.7/site-packages/gspread/httpsession.py", line 68, in request
    response = func(url, data=data, headers=request_headers)
  File "/Users/hans/Documents/workspace/nobo_python/env/lib/python2.7/site-packages/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/hans/Documents/workspace/nobo_python/env/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/hans/Documents/workspace/nobo_python/env/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Users/hans/Documents/workspace/nobo_python/env/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/Users/hans/Documents/workspace/nobo_python/env/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/Users/hans/Documents/workspace/nobo_python/env/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 361, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 869, in send
    self.sock.sendall(data)
  File "/Users/hans/Documents/workspace/nobo_python/env/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 292, in sendall
    sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
  File "/Users/hans/Documents/workspace/nobo_python/env/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 281, in _send_until_done
    return self.connection.send(data)
  File "/Users/hans/Documents/workspace/nobo_python/env/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1256, in send
    self._raise_ssl_error(self._ssl, result)
  File "/Users/hans/Documents/workspace/nobo_python/env/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1166, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (32, 'EPIPE')
```
### PIP info
```
cffi==1.9.1
cryptography==1.7
enum34==1.1.6
gspread==0.5.0
httplib2==0.9.2
idna==2.1
ipaddress==1.0.17
oauth2client==1.5.2
psycopg2==2.6.2
pyasn1==0.1.9
pyasn1-modules==0.0.8
pycparser==2.17
pymongo==3.4.0
pyOpenSSL==16.2.0
pytz==2016.10
requests==2.12.3
rsa==3.4.2
schedule==0.4.2
six==1.10.0
```

**Comment by burnash** [comment]
> Current workaround is to update the cells to blank

Does it mean calling Worksheet.update_cells() works correctly in your case? Without this ssl error?

**Comment by helgisteinar** [comment]
yes, no problem.

**Comment by burnash** [comment]
Recreated the sheet with 12 cols, 150 rows, but I can't reproduce the error. What is the index of a row you're trying to delete?

**Comment by helgisteinar** [comment]
My first dataset has 152 rows, the next one came with 146, so I wanted to delete rows 147-152.

I did find a reference to some problems with the `request` library (related to boto3 project) but unable to replicate that one.

**Comment by burnash** [comment]
I've seen related issues in boto too. It looks like something is wrong with pyopenssl.

**Comment by neeljpatel** [comment]
Was this issue resolved or is there a work around? I'm able to call clear() on one of my worksheets, but fails on another in the same spreadsheet.
