### ISSUE TITLE
[Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by joshjacobson** [burnash/gspread#468]
```
scope = ['https://spreadsheets.google.com/feeds']
creds = ServiceAccountCredentials.from_json_keyfile_name('NFL Redraft-e021dc0d5969.json', scope)
client = gspread.authorize(creds)
```

This code is working well on my local machine, but it is failing on PythonAnywhere with `OSError: [Errno 101] Network is unreachable`

[Image with Full Error Trace](http://i.imgur.com/tbKGM4o.png)

Any idea how to resolve?

**Comment by petrNikolaev1** [comment]
The same problem. Did you cope with it?

**Comment by joshjacobson** [comment]
@petrNikolaev1  Upgrading my hosting from a free to paid tier resolved the error.

**Comment by petrNikolaev1** [comment]
@joshjacobson Thank you for your answer!! However, it is sad:(

**Comment by OmarIbannez** [comment]
I have this same problem, I think is related to the proxy issue, what can I do?

**Comment by petrNikolaev1** [comment]
Well, now I am using developerKey instead of authentication with
credentials and it is much better

2017-07-22 2:59 GMT+08:00 Omar Ibañez <notifications@github.com>:

**Comment by chanduch06** [comment]
Hi i'm also getting same issue, I think it's due to proxy, even  if i'm giving proxy details, it's throwing the same error
'''Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1252, in connect
    super().connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable
'''

**Comment by burnash** [comment]
@joshjacobson I'm not sure this is a solely gspread's issue. Should we close it?

**Comment by burnash** [comment]
I'm closing this issue due to inactivity. Feel free to reopen it if you have an update.

**Comment by TechTard88** [comment]
I'm getting this same error, please help.... Im on ubuntu 18; tryna get twitter pypi to post a tweet. it worked yesterday now it does this error....

**Comment by burnash** [comment]
To clarify this: as the title of the error says, *the network is unreachable* and it means that there is a problem with the connection to the Internet – probably due to network or proxy settings.

Depending on your operating system you may use different methods to troubleshoot network connection:

1. [Linux](https://www.google.com/?q=troubleshoot+network+connection+linux)
2. [macOS](https://www.google.com/?q=troubleshoot+network+connection+macos)
3. [Windows](https://www.google.com/?q=troubleshoot+network+connection+windows)

If you're using Proxy, try [debugging the network proxy](https://www.google.com/?q=debugging++the+network+proxy).
