### ISSUE TITLE
I cant do gspread.login(user, pass)

### ISSUE THREAD

**Issue by saDonahue** [burnash/gspread#477]
I am trying to login with gspread using the login function but I keep getting this:
Traceback (most recent call last):
  File "C:/Users/Sammy D/PycharmProjects/Auto Inventory/main/Main.py", line 34, in <module>
    upload(compInfo)
  File "C:/Users/Sammy D/PycharmProjects/Auto Inventory/main/Main.py", line 21, in upload
    sheet=gspread.login('saXXXXXXX@XXXX.com', 'xxxxxxx')
AttributeError: module 'gspread' has no attribute 'login'

**Comment by seppestas** [comment]
This is correct, the `gspread` module does not have a login function. You should authorize using [`gspread.authorize(credentials)`](https://gspread.readthedocs.io/en/latest/#gspread.authorize), which will automatically create and login a gspread client using an [oAuth2 client](https://github.com/google/oauth2client).

For more information on how to do this see http://gspread.readthedocs.io/en/latest/oauth2.html
