### ISSUE TITLE
update_cells throwing AttributeError for simple update

### ISSUE THREAD

**Issue by Chaffelson** [burnash/gspread#483]
### Environment info

Operating System: OSX
Python version: 3.6
gspread version: PyPi latest: 0.6.2

### Steps to reproduce
```
import gspread
scope = ['https://spreadsheets.google.com/feeds']
credentials = ServiceAccountCredentials.from_json_keyfile_dict(_config['sheets_auth'], scope)
_gc = gspread.authorize(credentials=credentials)
_gs = _gc.open_by_key('sheet_id')
ws = _gs.worksheet('balances')
currencies = ws.col_values(1)  # list of all values in ColA
next_empty_row_index = currencies.index('')  # list index of next empty row in ColA
block = ws.range('A1:B50')  # List of pairs of all cells from A1:B1 through to A50:B50
if next_empty_row_index is 0:
    #  virgin sheet, so set header row
    block[next_empty_row_index] = 'Currency'
    block[next_empty_row_index +1] = 'Amount'
    next_empty_row_index += 2
ws.update_cells(block)
```

### Stack trace or other output that would be helpful
```
Traceback (most recent call last):
  File "/Users/dchaffey/.virtualenvs/cryptohands_py3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-49-d9ef8975ee68>", line 1, in <module>
    ws.update_cells(block)
  File "/Users/dchaffey/.virtualenvs/cryptohands_py3/lib/python3.6/site-packages/gspread/models.py", line 554, in update_cells
    feed = self._create_update_feed(cell_list)
  File "/Users/dchaffey/.virtualenvs/cryptohands_py3/lib/python3.6/site-packages/gspread/models.py", line 531, in _create_update_feed
    SubElement(entry, 'batch:id').text = cell.element.find(
AttributeError: 'str' object has no attribute 'element'
```

**Comment by Chaffelson** [comment]
Troubleshooted myself - error occurs if you assign the value directly to the list item in the block, rather than explicitly to the value element
This works:

```
block[next_empty_row_index].value = 'Currency'
```
