### ISSUE TITLE
installation issue: BadZipfile: File is not a zip file

### ISSUE THREAD

**Issue by jrheard** [burnash/gspread#521]
hi - i can't install gspread 2.0.0 on a raspberry pi:

### Environment info

Operating System: raspbian stretch
Python version: 2.7.13
gspread version: 2.0.0

### Steps to reproduce
1. `pip install --user gspread`

### Stack trace or other output that would be helpful

```
pi@senior-design-pi-2:~ $ pip install --user gspread
Collecting gspread
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 809, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 715, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/usr/lib/python2.7/dist-packages/pip/utils/__init__.py", line 617, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/usr/lib/python2.7/dist-packages/pip/utils/__init__.py", line 502, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 813, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
```

**Comment by lavigne958** [comment]
Very old version of gspread, new releases have been released, that could be a one time network error or a corrupted package on repository or corrupted flash memory card on you raspberryPi.

Just tried it on a computer and it works well with latest version.

If you still encounter this issue please let us know we'll look at it

Closing this issue.
