### ISSUE TITLE
KeyError when calling update_cell API with unicode sheetname

### ISSUE THREAD

**Issue by ckclark** [burnash/gspread#544]
### Environment info

Operating System: Ubuntu
Python version: 2.7.13
gspread version: 3.0.0

### Steps to reproduce
1. Create a workbook with sheet name in unicode like 中文
2. Just execute
```python
sheet = wb.worksheet(u'中文')
sheet.update_cell(1, 1, 'test2')
```

### Stack trace or other output that would be helpful

```
Traceback (most recent call last):
  File "gspread_bug.py", line 24, in <module>
    main()
  File "gspread_bug.py", line 21, in main
    sheet.update_cell(1, 1, 'test2')
  File "/tmp/gspread/local/lib/python2.7/dist-packages/gspread/models.py", line 567, in update_cell
    'values': [[value]]
  File "/tmp/gspread/local/lib/python2.7/dist-packages/gspread/models.py", line 114, in values_update
    url = SPREADSHEET_VALUES_URL % (self.id, quote(range, safe=''))
  File "/usr/lib64/python2.7/urllib.py", line 1299, in quote
    return ''.join(map(quoter, s))
KeyError: u'\u4e2d'
```

### Possible fix
 I tweak a little at [models.py#114](https://github.com/burnash/gspread/blob/master/gspread/models.py#L114) to
`url = SPREADSHEET_VALUES_URL % (self.id, quote(range.encode('UTF-8'), safe=''))`
and it will work. Hope this helps.

**Comment by burnash** [comment]
Thank you for reporting this, I can confirm the bug.
