### ISSUE TITLE
Connection fails

### ISSUE THREAD

**Issue by super-nathan** [burnash/gspread#594]
This used to work, and now it doesnt. I dont think I changed anything other than normal updates.

The script that is calling it: https://github.com/super-nathan/Barrel-House-Monitor/blob/master/spreadsheet.py

### Environment info

Operating System: Raspberry Pi Raspbian
Python version: current (just updated)
gspread version: current (just updated)

### Steps to reproduce
1.try to run a script which uses gspread

### Stack trace or other output that would be helpful

Traceback (most recent call last):
  File "/usr/bin/spreadsheet.py", line 163, in <module>
    sheet.insert_row(row, index=2)
  File "/usr/local/lib/python2.7/dist-packages/gspread/models.py", line 668, in insert_row
    self.update_cells(cells_after_insert)
  File "/usr/local/lib/python2.7/dist-packages/gspread/models.py", line 555, in update_cells
    self.client.post_cells(self, ElementTree.tostring(feed))
  File "/usr/local/lib/python2.7/dist-packages/gspread/client.py", line 241, in post_cells
    r = self.session.post(url, data, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/gspread/httpsession.py", line 79, in post
    return self.request('POST', url, params=params, data=data, headers=headers, files=files, json=json)
  File "/usr/local/lib/python2.7/dist-packages/gspread/httpsession.py", line 65, in request
    response = func(url, data=data, params=params, headers=request_headers, files=files, json=json)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(32, 'Broken pipe'))

**Comment by burnash** [comment]
Thanks for reporting this.

Looks like you're actually using not the recent version of gsrpead (0.6.2?) I can see it from the stacktrace:

```
File "/usr/local/lib/python2.7/dist-packages/gspread/models.py", line 555, in update_cells
self.client.post_cells(self, ElementTree.tostring(feed))
```

`ElementTree` [was removed](https://github.com/burnash/gspread/commit/63fab93951991027224263793bdf4df7f79ec8d3#diff-32d879761dfc2378af26ee09994d1f3aL14) in 3.0.0

Please upgrade gspread and try again. I'm closing this issue for now. Feel free to reopen a new issue if you still experience the problem.
