### ISSUE TITLE
Google Sheet name is Chinese cause crash

### ISSUE THREAD

**Issue by shuai265** [burnash/gspread#605]
### Environment info

Operating System: OS X
Python version: 2.7.15
gspread version:  (3.0.1)

### Steps to reproduce
1.Set up a new sheet in google drive, change the sheet name into Chinese like '中文'.
2.Read value from the new sheet, then it will crash.
3.If I change the sheet name into English, the program will work all right.

![](https://ws1.sinaimg.cn/large/006tNbRwgy1fwb16zp462j30dz04qq33.jpg)

### Stack trace or other output that would be helpful
![](https://ws3.sinaimg.cn/large/006tNbRwgy1fwb19n07gcj31hi0bkwia.jpg)

**source code:**

```
gc = gspread.authorize(credentials)

# Open a worksheet from spreadsheet with one shot
wks = gc.open_by_url(url).sheet1

# Fetch a cell range
cell_list = wks.range('A1:B7')
```

**crash log:**
```
Traceback (most recent call last):
  File "*************.py", line 45, in <module>
    cell_list = wks.range('A1:B7')
  File "/usr/local/lib/python2.7/site-packages/gspread/utils.py", line 168, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/gspread/models.py", line 419, in range
    data = self.spreadsheet.values_get(range_label)
  File "/usr/local/lib/python2.7/site-packages/gspread/models.py", line 109, in values_get
    url = SPREADSHEET_VALUES_URL % (self.id, quote(range, safe=''))
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 1298, in quote
    return ''.join(map(quoter, s))
KeyError: u'\u4e2d'
```

**Comment by burnash** [comment]
Thank you for the detailed report. Looks like it's related to #558 and #554. The pr that fixes this is #596. I'll try to release this shortly. Please stay tuned :)
