### ISSUE TITLE
TypeError credentials

### ISSUE THREAD

**Issue by LucSpan** [burnash/gspread#635]
All used to work fine, but now I'm getting an error when I try to use the credentials. 

I've updated today to gspread 3.1.0 and oauth2client 4.1.3.

----------

**Code**

```
    os.chdir('/Users/path/to/client_secret.json')
    
    scope = ['https://spreadsheets.google.com/feeds']
    creds = ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope)

    gc = gspread.authorize(creds)
```

Running this code gives the following error,

  ```
  TypeError: super(type, obj): obj must be an instance or subtype of type
    
    Traceback (most recent call last):
    
      File "<ipython-input-182-3638a9b3d45b>", line 5, in <module>
        creds = ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope)
    
      File "/Applications/anaconda/lib/python3.6/site-packages/oauth2client/service_account.py", line 223, in from_json_keyfile_name
        revoke_uri=revoke_uri)
    
      File "/Applications/anaconda/lib/python3.6/site-packages/oauth2client/service_account.py", line 189, in _from_parsed_json_keyfile
        revoke_uri=revoke_uri)
    
      File "/Applications/anaconda/lib/python3.6/site-packages/oauth2client/service_account.py", line 108, in __init__
        revoke_uri=revoke_uri)
    
      File "/Applications/anaconda/lib/python3.6/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
        return wrapped(*args, **kwargs)
    
      File "/Applications/anaconda/lib/python3.6/site-packages/oauth2client/client.py", line 1472, in __init__
        super(AssertionCredentials, self).__init__(
    
    TypeError: super(type, obj): obj must be an instance or subtype of type
```

What is going wrong here?

**Comment by aminhakimsazali** [comment]
Did you able to solve this? I'm also facing the same error.

**Comment by lavigne958** [comment]
This is an issue related to [google-auth](https://github.com/googleapis/google-auth-library-python). Not to GSpread unfortunately.

If you don't mind I'll close this issue. You can still discuss the issue here if you wish.
