### ISSUE TITLE
oauth2client.client.HttpAccessTokenRefreshError: invalid_scope: http://www.googleapis.com/auth/drive is not a valid audience string, Getting this error why ?

### ISSUE THREAD

**Issue by samarthkansal** [burnash/gspread#642]
Hello, I am getting this error while authenticating my gspread credentials. I have made sure about the following things before asking this question here:
1) Google sheet and google Drive APIs are enabled in my console.
2) so are Google cloud storage and Google cloud storage json APIs enabled
3) The google sheet which i am trying to perform the gspread operations on is shared with the client_id(mentioned in json file,downloaded after i created my credentials from google console)
4) I am behind a proxy and i am using http_proxy and https_proxy env. variables

(I am unable to rid this error, Please help me fix this error, I am new to python. I read many answers on stackoverflow and github but nothing worked out for my case.)

**My Code:**
from oauth2client.service_account import ServiceAccountCredentials
import httplib2

import gspread

scope = ['http://www.googleapis.com/auth/drive']
credentials = ServiceAccountCredentials.from_json_keyfile_name('credential_token.json',scope)
print(credentials)
gs = gspread.authorize(credentials)

worksheet = gc.open('Project_Sheet').sheet1

print(wks.get_all_records())

**Error:**
Traceback (most recent call last):
  File "C:\Users\skansal\Desktop\Agile_Tool\Agile_Google_Sheets\Google_Api.py", line 10, in <module>
    gs = gspread.authorize(credentials)
  File "C:\Users\skansal\AppData\Local\Programs\Python\Python36\lib\site-packages\gspread\__init__.py", line 38, in authorize
    client.login()
  File "C:\Users\skansal\AppData\Local\Programs\Python\Python36\lib\site-packages\gspread\client.py", line 51, in login
    self.auth.refresh(http)
  File "C:\Users\skansal\AppData\Local\Programs\Python\Python36\lib\site-packages\oauth2client\client.py", line 545, in refresh
    self._refresh(http)
  File "C:\Users\skansal\AppData\Local\Programs\Python\Python36\lib\site-packages\oauth2client\client.py", line 749, in _refresh
    self._do_refresh_request(http)
  File "C:\Users\skansal\AppData\Local\Programs\Python\Python36\lib\site-packages\oauth2client\client.py", line 819, in _do_refresh_request
    raise HttpAccessTokenRefreshError(error_msg, status=resp.status)
oauth2client.client.HttpAccessTokenRefreshError: invalid_scope: http://www.googleapis.com/auth/drive is not a valid audience string.

**Comment by taxonmatic** [comment]
I had same problem and finally i solved it.
you focus on the web address.
what i mean is that 'http://~~~~' change to 'https://~~~~'.
So, you add spell 's' and the code is working.

**Comment by samarthkansal** [comment]
wow thanks it worked
