### ISSUE TITLE
Request had invalid authentication credentials.

### ISSUE THREAD

**Issue by mmphego** [burnash/gspread#686]
Authentication related issues when looping and updating google sheets.

Note: I have already increased the quotas on google dev project.

### Environment info

Operating System: Ubuntu 18.04.2 LTS
Python version: Python 3.6.7
gspread version: gspread==3.1.0

### Steps to reproduce
1. for i in range(130): update google sheet

### Stack trace or other output that would be helpful
```python
Traceback (most recent call last):
  File "./price_checker.py", line 74, in <module>
    main()
  File "./price_checker.py", line 70, in main
    price_updater.process_item_list()
  File "/home/mmphego/GitHub/Productivity_Projects/shopping_list_bot/shopping_list_bot/price_updater.py", line 159, in process_item_list
    prod_coord[0] + count, prod_coord[1], cart.item_name
  File "/home/mmphego/.venvs/venv3.6/lib/python3.6/site-packages/gspread/models.py", line 739, in update_cell
    'values': [[value]]
  File "/home/mmphego/.venvs/venv3.6/lib/python3.6/site-packages/gspread/models.py", line 176, in values_update
    r = self.client.request('put', url, params=params, json=body)
  File "/home/mmphego/.venvs/venv3.6/lib/python3.6/site-packages/gspread/client.py", line 79, in request
    raise APIError(response)
gspread.exceptions.APIError: {
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}
```

**Comment by mmphego** [comment]
Fixed...

**Comment by mik-laj** [comment]
@mmphego Can you provide a more information?

**Comment by mmphego** [comment]
> @mmphego Can you provide a more information?

On the fix or on the error log?

**Comment by TobKed** [comment]
> > @mmphego Can you provide a more information?
> 
> On the fix or on the error log?

About both please.
Is this issue connected with token expiration after one hour?
