### ISSUE TITLE
batch_update() "major_dimension" unexpected keyword argument

### ISSUE THREAD

**Issue by cryobry** [burnash/gspread#829]
**Describe the bug**
I am trying to use batch_update() method to update two columns of cells. The first column contains a list of golfer names and the second column is their associated winnings. The data is stored in a list of columns (lists) so I would like to use the "major_dimension='COLUMNS'" kwarg in batch_update. Unfortunately batch_update() is not accepting the major_dimension kwarg.

**To Reproduce**
MWE:

```
import gspread
from oauth2client.service_account import ServiceAccountCredentials

spreadsheet_key = '1BSj97V4g-nRlFAisDo_-X9igdFYN7599aPiNcDOfCQk' # 2020 Testing
json_keyfile = 'Masters Game-43f0cf61b4ed.json'

def getWorksheet(spreadsheet_key, json_keyfile):
    scope = ['https://spreadsheets.google.com/feeds',
            'https://www.googleapis.com/auth/drive']
    credentials = ServiceAccountCredentials.from_json_keyfile_name(json_keyfile, scope)
    gc = gspread.authorize(credentials)
    spreadsheet = gc.open_by_key(spreadsheet_key)
    worksheet = spreadsheet.get_worksheet(0)
    return worksheet

batch_update_list = [{'range': 'M3:N95', 'values': [['Dustin Johnson', 'Sungjae Im', 'Paul Casey', 'John Augenstein', 'Abraham Ancer', 'Cameron Smith', 'Dylan Frittelli', 'Webb Simpson', 'Xander Schauffele', 'Danny Willett', 'Phil Mickelson', 'Brooks Koepka', 'Christiaan Bezuidenhout', 'Bernhard Langer', 'Justin Thomas', 'Justin Rose', 'Hideki Matsuyama', 'Lee Westwood', 'Louis Oosthuizen', 'Patrick Reed', 'Tiger Woods', 'Sebastian Munoz', 'Rickie Fowler', 'Tommy Fleetwood', 'Adam Scott', 'Patrick Cantlay', 'Cameron Champ', 'Jazz Janewattananond', 'Jon Rahm', 'Tony Finau', 'Matt Wallace', 'C.T. Pan', 'Marc Leishman', 'Larry Mize', 'Matt Kuchar', 'Bryson DeChambeau', 'Jason Day', 'Si Woo Kim', 'Justin Harding', 'Byeong Hun An', 'Billy Horschel', 'Collin Morikawa', 'Victor Perez', 'Jimmy Walker', 'Charles Howell III', 'Brandt Snedeker', 'Kevin Kisner', 'Scottie Scheffler', 'Jason Kokrak', 'Henrik Stenson', 'Mike Weir', 'Shugo Imahira', 'Matthew Wolff', 'Bernd Wiesberger', 'Max Homa', 'Zach Johnson', 'Ian Poulter', 'Gary Woodland', 'Graeme McDowell', 'Nick Taylor', 'Chez Reavie', 'J.T. Poston', 'Rory McIlroy', 'Andrew Putnam', 'Kevin Na', 'Charl Schwartzel', 'Andy Ogletree', 'Rafa Cabrera Bello', 'Sung Kang', 'Bubba Watson', 'Tyrrell Hatton', 'Brendon Todd', 'Corey Conners', 'Adam Hadwin', 'Shane Lowry', 'Lanto Griffin', 'Jordan Spieth', 'Francesco Molinari', 'Matthew Fitzpatrick', 'James Sugrue', 'Vijay Singh', 'Nate Lashley', 'Lukas Michel', 'Erik van Rooyen', 'Fred Couples', 'Lucas Glover', 'Tyler Duncan', 'Jose Maria Olazabal', 'Sandy Lyle', 'Andrew Landry', 'Yuxin Lin', 'Abel Gallegos'], [2070000.0, 1012000.0, 1012000.0, 475333.3333333333, 475333.3333333333, 475333.3333333333, 358416.6666666667, 358416.6666666667, 358416.6666666667, 210833.33333333334, 210833.33333333334, 210833.33333333334, 210833.33333333334, 210833.33333333334, 210833.33333333334, 210833.33333333334, 210833.33333333334, 210833.33333333334, 210833.33333333334, 210833.33333333334, 210833.33333333334, 96025.0, 96025.0, 96025.0, 96025.0, 96025.0, 96025.0, 96025.0, 96025.0, 96025.0, 96025.0, 62428.57142857143, 62428.57142857143, 62428.57142857143, 62428.57142857143, 62428.57142857143, 62428.57142857143, 62428.57142857143, 37126.92307692308, 37126.92307692308, 37126.92307692308, 37126.92307692308, 37126.92307692308, 37126.92307692308, 37126.92307692308, 37126.92307692308, 37126.92307692308, 37126.92307692308, 37126.92307692308, 37126.92307692308, 37126.92307692308, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000]]}]

def batchUpdate(worksheet, batch_update_list):
    worksheet.batch_update(batch_update_list, major_dimension="COLUMNS", value_input_option="USER_ENTERED")

if __name__ == '__main__':
    worksheet = getWorksheet(spreadsheet_key, json_keyfile)
    batchUpdate(worksheet, batch_update_list)
```

**Expected behavior**
The M column is filled from top to bottom with a list of player names and the N column is filled with their associated winnings.

**Environment info:**
- Fedora 33
- Python 3.9.0
- gspread 3.6.0

**Stack trace or other output that would be helpful**
```
Traceback (most recent call last):
  File "/home/bryan/Documents/develop/golf-game/game.py", line 224, in <module>
    batchUpdate(batch_update_list)
  File "/home/bryan/Documents/develop/golf-game/game.py", line 198, in batchUpdate
    worksheet.batch_update(batch_update_list, major_dimension="COLUMNS", value_input_option="USER_ENTERED")
  File "/home/bryan/.virtualenvs/masters-game/lib/python3.9/site-packages/gspread/utils.py", line 587, in wrapper
    raise TypeError(err % (f.__name__, list(unexpected_kwargs)))
TypeError: batch_update got unexpected keyword arguments: ['major_dimension']
(masters-game) [bryan@laptop]~/develop/golf-game$ /home/bryan/.virtualenvs/masters-game/bin/python /home/bryan/Documents/develop/golf-game/mwe-batchupdate.py
Traceback (most recent call last):
  File "/home/bryan/Documents/develop/golf-game/mwe-batchupdate.py", line 28, in <module>
    batchUpdate(batch_update_list)
  File "/home/bryan/Documents/develop/golf-game/mwe-batchupdate.py", line 23, in batchUpdate
    worksheet.batch_update(batch_update_list, major_dimension="COLUMNS", value_input_option="USER_ENTERED")
  File "/home/bryan/.virtualenvs/masters-game/lib/python3.9/site-packages/gspread/utils.py", line 587, in wrapper
    raise TypeError(err % (f.__name__, list(unexpected_kwargs)))
TypeError: batch_update got unexpected keyword arguments: ['major_dimension']
```

**Comment by olt96asc** [comment]
having the same issue. 
Looking at the batch update code, the major_dimension argument is neither accepted nor used. 
this is either a mistake in the documentation or the code
