### ISSUE TITLE
Can't read file: **AttributeError: '_RSAPrivateKey' object has no attribute 'sign'**

### ISSUE THREAD

**Issue by snusnuz** [burnash/gspread#841]
The same piece of code runs smoothly on another ubuntu VM.
Typing pip3 list on both environments shows the same packages installed (but different versions)

Any help in how to debug it? I'm a beginner.
---------------------------------
```
import gspread
gc = gspread.service_account(filename='/home/ubuntu/Test/credentialsnew.json')
#Open Google spreadsheet
sh = gc.open_by_key("1lrBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx") #my sheet
print(sh)
```
---------------------------------
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/gspread/models.py", line 94, in title
    return self._properties['title']
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "freegoodz/py/test_gspread.py", line 11, in <module>
    print(sh)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/gspread/models.py", line 132, in __repr__
    repr(self.title),
  File "/home/ubuntu/.local/lib/python3.5/site-packages/gspread/models.py", line 96, in title
    metadata = self.fetch_sheet_metadata()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/gspread/models.py", line 265, in fetch_sheet_metadata
    r = self.client.request('get', url, params=params)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/gspread/client.py", line 67, in request
    headers=headers,
  File "/home/ubuntu/.local/lib/python3.5/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/google/auth/transport/requests.py", line 460, in request
    self.credentials.before_request(auth_request, method, url, request_headers)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/google/auth/credentials.py", line 133, in before_request
    self.refresh(request)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/google/oauth2/service_account.py", line 360, in refresh
    assertion = self._make_authorization_grant_assertion()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/google/oauth2/service_account.py", line 354, in _make_authorization_grant_assertion
    token = jwt.encode(self._signer, payload)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/google/auth/jwt.py", line 112, in encode
    signature = signer.sign(signing_input)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/google/auth/crypt/_cryptography_rsa.py", line 112, in sign
    return self._key.sign(message, _PADDING, _SHA256)
**AttributeError: '_RSAPrivateKey' object has no attribute 'sign'**
```

Updated: add formating for stack Trace.

**Comment by lavigne958** [comment]
Hi could you please double check the service Account file you are using? Make sure it is the right one, and you script has access to it (the script is allowed to read the file content).

You mentioned 2 différents version of gspread, could please print both version number here for reference?

**Comment by lavigne958** [comment]
closing for inactivity.
