### ISSUE TITLE
import_csv: UnicodeEncodeError: 'latin-1' codec can't encode character

### ISSUE THREAD

**Issue by sam-watkins-sr** [burnash/gspread#867]
**Describe the bug**
The `import_csv` function fails with unicode input.

**To Reproduce**
`python3.9 -c 'import gspread; gspread.oauth().import_csv("Test", "—")'`

**Expected behavior**
It should import the UTF-8 CSV file without error.

**Code example***
As above.

**Screenshots**
N/A

**Environment info:**
- Operating System: Debian 11 bullseye
- Python version: 3.9.2
- gspread version: 3.7.0

**Stack trace or other output that would be helpful**
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/sam/.local/lib/python3.9/site-packages/gspread/client.py", line 294, in import_csv
    self.request(
  File "/home/sam/.local/lib/python3.9/site-packages/gspread/client.py", line 64, in request
    response = getattr(self.session, method)(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 602, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/home/sam/.local/lib/python3.9/site-packages/google/auth/transport/requests.py", line 482, in request
    response = super(AuthorizedSession, self).request(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/sam/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/sam/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1300, in _send_request
    body = _encode(body, 'body')
  File "/usr/lib/python3.9/http/client.py", line 164, in _encode
    raise UnicodeEncodeError(
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2014' in position 0: Body ('—') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
`

**Additional context**
N/A

**Comment by pocin** [comment]
Hit this today as well. It seems the default encoding for `http` dependency is `latin-1`. 
For anyone that comes forward and uploading a csv from file just do 
```
with open("path.csv", "rb") as fb:
    gspread.oauth().import_csv("sheet_id", fb)
```
the default encoding when reading in binary mode is `utf8`. 
Perhaps emit a warning in `import_csv()`?

**Comment by lavigne958** [comment]
After checking when opening any file using `open("file.csv")` using binary mode or not the default mode is "utf-8".
What we could do is:

- check if data input is a string and then force encode it in "utf-8".

that should work and should not break anything.
