### ISSUE TITLE
Firewall issues?

### ISSUE THREAD

**Issue by almartin82** [burnash/gspread#91]
Hi Burnash,

Love the library -- incredibly simple - was up and running in no time.

Issue I'm running into is that I'm trying to deploy a script to a Windows server and am seeing timeout errors that I'm pretty certain are related to my firewall.

```python
Traceback (most recent call last):
  File "C:\data_robot\google_docs\get_riseXC.py", line 76, in <module>
    main()
  File "C:\data_robot\google_docs\get_riseXC.py", line 36, in main
    sht = gc.open_by_key('REDACTED')
  File "C:\Python27\lib\site-packages\gspread\client.py", line 145, in open_by_key
    feed = self.get_spreadsheets_feed()
  File "C:\Python27\lib\site-packages\gspread\client.py", line 198, in get_spreadsheets_feed
    r = self.session.get(url)
  File "C:\Python27\lib\site-packages\gspread\httpsession.py", line 68, in get
    return self.request('get', url, **kwargs)
  File "C:\Python27\lib\site-packages\gspread\httpsession.py", line 63, in request
    return request.urlopen(req)
  File "C:\Python27\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10053] An established connection was aborted by the software in your host machine>
```

Per SO (http://stackoverflow.com/questions/13798774/which-ports-will-python-use-to-send-html-request-with-urllib-or-urllib2) I think I need to figure out what ports need to be opened up, but I'm not sure how to go about doing that.

Any advice about how to figure out what port range I need?  I've used BeautifulSoup to pull down content from the web on this machine, so I'm assuming standard web ports are already open.

Thanks!

**Comment by msuozzo** [comment]
Sorry no one was able to help you @almartin82 (and sorry this response is a couple years late).

I doubt ports are the issue here (although I could be wrong). Has this issue persisted?

**Comment by burnash** [comment]
@almartin82 Sorry again for the late response. Did you figure out the source of the problem? This looks like it's firewall related.
