### ISSUE TITLE
Error on running working for more than an hour on linux server google.auth.exceptions.TransportError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by jo-mamaa** [burnash/gspread#955]
**Describe the bug**
I have an async loop running in my program, it's meant to be running constantly, but ~1h into it, it errors out with : google.auth.exceptions.TransportError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
This doesn't happen on my PC, but only when I'm running it on my linux server. I've checked everywhere I could, but can't find anything limiting it in the servers' network settings

**To Reproduce**
1. Async loop (currently using discord.py tasks.loop()) that runs every hour.
2. This is supposed to update a cell in my sheet with the current time to make sure that the program is online, full traceback will be at the bottom of this issue (running 2 loops, the other just gets some information from a sheet each hour, for which the traceback is given)

**Expected behavior**
It to run without raising fatal errors.

**Code example***
If applicable, provide a code example to help explain your problem.
It's just a loop that does stuff if a condition is true, and after that, this:
rl=sheet.find(sheet.col_values(3)[3:][-1]).row

**Environment info:**
google-auth==2.3.2
google-auth-oauthlib==0.4.6
gspread==4.0.1

OS = Ubuntu 20.04.3
Python = 3.8.10

**Stack trace or other output that would be helpful**
```
Unhandled exception in internal background task 'LBLOOP'.
Nov 17 15:57:40 koi1 python3[407136]: Traceback (most recent call last):
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
Nov 17 15:57:40 koi1 python3[407136]:     httplib_response = self._make_request(
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
Nov 17 15:57:40 koi1 python3[407136]:     six.raise_from(e, None)
Nov 17 15:57:40 koi1 python3[407136]:   File "<string>", line 3, in raise_from
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
Nov 17 15:57:40 koi1 python3[407136]:     httplib_response = conn.getresponse()
Nov 17 15:57:40 koi1 python3[407136]:   File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
Nov 17 15:57:40 koi1 python3[407136]:     response.begin()
Nov 17 15:57:40 koi1 python3[407136]:   File "/usr/lib/python3.8/http/client.py", line 307, in begin
Nov 17 15:57:40 koi1 python3[407136]:     version, status, reason = self._read_status()
Nov 17 15:57:40 koi1 python3[407136]:   File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
Nov 17 15:57:40 koi1 python3[407136]:     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
Nov 17 15:57:40 koi1 python3[407136]:   File "/usr/lib/python3.8/socket.py", line 669, in readinto
Nov 17 15:57:40 koi1 python3[407136]:     return self._sock.recv_into(b)
Nov 17 15:57:40 koi1 python3[407136]:   File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
Nov 17 15:57:40 koi1 python3[407136]:     return self.read(nbytes, buffer)
Nov 17 15:57:40 koi1 python3[407136]:   File "/usr/lib/python3.8/ssl.py", line 1099, in read
Nov 17 15:57:40 koi1 python3[407136]:     return self._sslobj.read(len, buffer)
Nov 17 15:57:40 koi1 python3[407136]: ConnectionResetError: [Errno 104] Connection reset by peer
Nov 17 15:57:40 koi1 python3[407136]: During handling of the above exception, another exception occurred:
Nov 17 15:57:40 koi1 python3[407136]: Traceback (most recent call last):
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
Nov 17 15:57:40 koi1 python3[407136]:     resp = conn.urlopen(
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
Nov 17 15:57:40 koi1 python3[407136]:     retries = retries.increment(
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
Nov 17 15:57:40 koi1 python3[407136]:     raise six.reraise(type(error), error, _stacktrace)
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
Nov 17 15:57:40 koi1 python3[407136]:     raise value.with_traceback(tb)
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
Nov 17 15:57:40 koi1 python3[407136]:     httplib_response = self._make_request(
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
Nov 17 15:57:40 koi1 python3[407136]:     six.raise_from(e, None)
Nov 17 15:57:40 koi1 python3[407136]:   File "<string>", line 3, in raise_from
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
Nov 17 15:57:40 koi1 python3[407136]:     httplib_response = conn.getresponse()
Nov 17 15:57:40 koi1 python3[407136]:   File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
Nov 17 15:57:40 koi1 python3[407136]:     response.begin()
Nov 17 15:57:40 koi1 python3[407136]:   File "/usr/lib/python3.8/http/client.py", line 307, in begin
Nov 17 15:57:40 koi1 python3[407136]:     version, status, reason = self._read_status()
Nov 17 15:57:40 koi1 python3[407136]:   File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
Nov 17 15:57:40 koi1 python3[407136]:     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
Nov 17 15:57:40 koi1 python3[407136]:   File "/usr/lib/python3.8/socket.py", line 669, in readinto
Nov 17 15:57:40 koi1 python3[407136]:     return self._sock.recv_into(b)
Nov 17 15:57:40 koi1 python3[407136]:   File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
Nov 17 15:57:40 koi1 python3[407136]:     return self.read(nbytes, buffer)
Nov 17 15:57:40 koi1 python3[407136]:   File "/usr/lib/python3.8/ssl.py", line 1099, in read
Nov 17 15:57:40 koi1 python3[407136]:     return self._sslobj.read(len, buffer)
Nov 17 15:57:40 koi1 python3[407136]: urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Nov 17 15:57:40 koi1 python3[407136]: During handling of the above exception, another exception occurred:
Nov 17 15:57:40 koi1 python3[407136]: Traceback (most recent call last):
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/venv/lib/python3.8/site-packages/google/auth/transport/requests.py", line 183, in __call__
Nov 17 15:57:40 koi1 python3[407136]:     response = self.session.request(
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
Nov 17 15:57:40 koi1 python3[407136]:     resp = self.send(prep, **send_kwargs)
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
Nov 17 15:57:40 koi1 python3[407136]:     r = adapter.send(request, **kwargs)
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/venv/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
Nov 17 15:57:40 koi1 python3[407136]:     raise ConnectionError(err, request=request)
Nov 17 15:57:40 koi1 python3[407136]: requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Nov 17 15:57:40 koi1 python3[407136]: The above exception was the direct cause of the following exception:
Nov 17 15:57:40 koi1 python3[407136]: Traceback (most recent call last):
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/venv/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
Nov 17 15:57:40 koi1 python3[407136]:     await self.coro(*args, **kwargs)
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/LB.py", line 106, in LBLOOP
Nov 17 15:57:40 koi1 python3[407136]:     self.GETINFO()
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/LB.py", line 81, in GETINFO
Nov 17 15:57:40 koi1 python3[407136]:     rl=sheet.find(sheet.col_values(3)[3:][-1]).row
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/venv/lib/python3.8/site-packages/gspread/models.py", line 987, in col_values
Nov 17 15:57:40 koi1 python3[407136]:     data = self.spreadsheet.values_get(
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/venv/lib/python3.8/site-packages/gspread/models.py", line 221, in values_get
Nov 17 15:57:40 koi1 python3[407136]:     r = self.client.request('get', url, params=params)
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/venv/lib/python3.8/site-packages/gspread/client.py", line 64, in request
Nov 17 15:57:40 koi1 python3[407136]:     response = getattr(self.session, method)(
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/venv/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
Nov 17 15:57:40 koi1 python3[407136]:     return self.request('GET', url, **kwargs)
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/venv/lib/python3.8/site-packages/google/auth/transport/requests.py", line 476, in request
Nov 17 15:57:40 koi1 python3[407136]:     self.credentials.before_request(auth_request, method, url, request_headers)
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/venv/lib/python3.8/site-packages/google/auth/credentials.py", line 133, in before_request
Nov 17 15:57:40 koi1 python3[407136]:     self.refresh(request)
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/venv/lib/python3.8/site-packages/google/oauth2/service_account.py", line 410, in refresh
Nov 17 15:57:40 koi1 python3[407136]:     access_token, expiry, _ = _client.jwt_grant(
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/venv/lib/python3.8/site-packages/google/oauth2/_client.py", line 193, in jwt_grant
Nov 17 15:57:40 koi1 python3[407136]:     response_data = _token_endpoint_request(request, token_uri, body)
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/venv/lib/python3.8/site-packages/google/oauth2/_client.py", line 161, in _token_endpoint_request
Nov 17 15:57:40 koi1 python3[407136]:     response_status_ok, response_data = _token_endpoint_request_no_throw(
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/venv/lib/python3.8/site-packages/google/oauth2/_client.py", line 115, in _token_endpoint_request_no_throw
Nov 17 15:57:40 koi1 python3[407136]:     response = request(method="POST", url=token_uri, headers=headers, body=body)
Nov 17 15:57:40 koi1 python3[407136]:   File "/srv/crazy/venv/lib/python3.8/site-packages/google/auth/transport/requests.py", line 189, in __call__
Nov 17 15:57:40 koi1 python3[407136]:     six.raise_from(new_exc, caught_exc)
Nov 17 15:57:40 koi1 python3[407136]:   File "<string>", line 3, in raise_from
Nov 17 15:57:40 koi1 python3[407136]: google.auth.exceptions.TransportError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by lavigne958** [comment]
Hi @jo-mamaa when your connection gets the above error message `connection reset by peer` it's because the server closed the connection and did not wait for you to finish your request. There is not much we can do about it sorry.

closing this issue.
